### ISSUE TITLE
docassemble-site.conf is missing from the repository

### ISSUE THREAD

**Issue by tawkir-syed** [jhpyle/docassemble#10]
I'm not sure what to do about this. I am following the installation guide but I am stuck at the point below:

sudo cp ./docassemble/Docker/docassemble-site.conf /etc/apache2/sites-available/docassemble.conf

You appear to not have docassemble-site.conf in github. 

I am stuck on this point in my installation. Thank you for this sharing this. I am looking forward to using this.

**Comment by jhpyle** [comment]
Sorry about that!  The file you are looking for is `./docassemble/Docker/config/docassemble-http.conf.dist`.  There is also an SSL version of the Apache configuration file in the same subdirectory.  I updated the documentation.  Thanks for pointing out the error!

**Comment by tawkir-syed** [comment]
Thank you very much for helping with that so quickly.
