### ISSUE TITLE
 Feature Request: Tab Indexing on Multiple Choice and Checkboxes

### ISSUE THREAD

**Issue by kgarner7** [jhpyle/docassemble#105]
Tested in: Firefox (63), Chrome (70) on Docassemble 0.3.7

I have noticed that, when including multiple choice radio buttons or check boxes, there does not appear to be a way to use tab to access the fields. It would be nice if it was possible that you could use tab with a combination of the arrow keys to set the values of these fields, rather than having to depend on a mouse.

**Comment by jhpyle** [comment]
Tab and shift-tab can now be used with multiple-choice fields.  I did not implement cursor key navigation of multiple choice items; the tab and shift-tab are standard for this purpose, and cursor keys already have a purpose for scrolling the page, so I did not want to interfere with those defaults in this context.
