### ISSUE TITLE
Error on docx file upload using wizard

### ISSUE THREAD

**Issue by dwmcqueen** [jhpyle/docassemble#108]
When I get to the step to upload the Word file in the Playground wizard, I get the attached error.
[Document assembly wizard.pdf](https://github.com/jhpyle/docassemble/files/2658919/Document.assembly.wizard.pdf)

**Comment by jhpyle** [comment]
What Word file did you upload?  One that you made?

**Comment by dwmcqueen** [comment]
Ugh - sorry - I had it as docm and not docx.

Works now.
