### ISSUE TITLE
Internationalize basic_questions.yml

### ISSUE THREAD

**Issue by Gauntlet173** [jhpyle/docassemble#115]
Right now basic_questions.yml presumes that the Individual and the Case is in the United States.

There are a couple of options.  We could either modify basic_questions.yml with the correct information for additional jurisdictions, or we could add localized versions like basic_questions_ca.yml for Canada, etc.

Interested in thoughts on which would be the better approach.

**Comment by jhpyle** [comment]
I think the best way to do it is:
```
include:
  - docassemble.base:basic-questions.yml
  - docassemble.canada:basic-questions.yml
```
The `question` and `code` blocks in the second file would take precedence over the first, so they could override particular functionality when necessary for localization.

A lot could be done to improve `docassemble.base:data/questions/basic-questions.yml`; I haven't worked on it in a long time.

Another area that can use some work is the `docassemble.base.legal` module.  I would encourage people to take the idea of this and expand it for their jurisdictions.  Then if we collect several examples, we can see if we could agree on a convenient set of objects and methods for the litigation domain.  This would hopefully be international.  Note that the `docassemble.base.legal` module has the beginnings of a "hook" system, which is kind of complicated but is potentially very useful for developing "universal" methods like `case.caption()`.
