### ISSUE TITLE
api_verify is returning TypeError: cannot use string pattern on a bytes-like object

### ISSUE THREAD

**Issue by wesleyatci** [jhpyle/docassemble#119]
Here's the error I'm getting when trying to hit the API URL  http://localhost:8000/api/list?key=1E3R9E8E61NXU9Y0OSYSWEBNHGDQK0ZH

  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/docassemble/webapp/server.py", line 18038, in api_verify
    m = re.match('da:api:userid:([0-9]+):key:' + api_key + ':info', rkeys[0])

Converting the rkeys[0] like below seems to fix it.

    m = re.match('da:api:userid:([0-9]+):key:' + api_key + ':info', rkeys[0].decode('utf-8'))

**Comment by jhpyle** [comment]
Thanks!  This is fixed in 0.4.5.
