### ISSUE TITLE
Error trying to start Docker container from a backup

### ISSUE THREAD

**Issue by dops0** [jhpyle/docassemble#120]
Hi,

We're trying to launch the latest version of the Docassemble Docker container from backup data created using the previous version. 

We hit an error and the initialize.sh script fails with the following error message. It appears like it's some kind of a unicode error raised by Python, but not really sure. 

Any idea what's going on here ?

`
2019-02-25T21:37:12 Successfully installed atomicwrites-1.3.0
2019-02-25T21:37:12 Cleaning up...
2019-02-25T21:37:12 Removed build tracker '/tmp/pip-req-tracker-Pmc00o'

returnval is: 0
install_package: done
check_for_updates: return value was 0
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
check_for_updates: real name of package atomicwrites is atomicwrites
update_versions: starting
get_installed_distributions: starting
get_installed_distributions: pip version:
pip 19.0.3 from /usr/share/docassemble/local/lib/python2.7/site-packages/pip (python 2.7)
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
get_installed_distributions: ending
add_dependencies: starting
get_installed_distributions: starting
get_installed_distributions: pip version:
pip 19.0.3 from /usr/share/docassemble/local/lib/python2.7/site-packages/pip (python 2.7)
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
get_installed_distributions: ending
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/share/docassemble/local/lib/python2.7/site-packages/docassemble/webapp/update.py", line 591, in <module>
    check_for_updates(doing_startup=True)
  File "/usr/share/docassemble/local/lib/python2.7/site-packages/docassemble/webapp/update.py", line 310, in check_for_updates
    add_dependencies(package_owner.get(package.id, 1))
  File "/usr/share/docassemble/local/lib/python2.7/site-packages/docassemble/webapp/update.py", line 365, in add_dependencies
    pip_info = get_pip_info(package.key)
  File "/usr/share/docassemble/local/lib/python2.7/site-packages/docassemble/webapp/update.py", line 555, in get_pip_info
    output = subprocess.check_output(['pip', 'show', package_name]).decode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 164: ordinal not in range(128)
`

**Comment by dops0** [comment]
Ok. Answering my own question. Setting the environment variable DAPYTHONVERSION=3 fixes the issue. Looks like the error occurs only when using Python 2.7

**Comment by jhpyle** [comment]
Unicode is treated differently in Python 2 and 3.  The source of the problem was a Python package you had installed that resulted in `pip show` output containing a character that could not be decoded.  I added some code to 0.4.9 that may make it work in Python 2.7.  But if you can get everything to work in Python 3 you should stick with Python 3.
