### ISSUE TITLE
Question: Docker start up times?

### ISSUE THREAD

**Issue by jrmiller82** [jhpyle/docassemble#125]
Hi! Been a few years since I checked in on docassemble; I have some slow time in my practice and I'm looking at adding it. 

I spun up a 2GB ram linode VPS and it's taking over 10 minutes from `docker run` to getting to the web app working. Is it just my hardware? Or is that expected time? I don't remember it taking anywhere near as long a few years ago to launch on older slower hardware.

**Comment by jhpyle** [comment]
I updated the documentation.  The initial boot process might take up to 20 minutes.  The bottleneck is Python's `pip` command.

**Comment by myaptad** [comment]
Is there a way to get more information while the startup is happening to ensure that system is not stuck during the start. What logs, if any, can be checked to track the progress of the DA start?

**Comment by myaptad** [comment]
Never mind on this.

It's listed in detail here https://docassemble.org/docs/docker.html#troubleshooting
