### ISSUE TITLE
Date entry? (perhaps Firefox Date picker issue?)

### ISSUE THREAD

**Issue by jrmiller82** [jhpyle/docassemble#128]
When I click on a date entry, I get a double dropdown for month and year, but it's clunky, and then exiting it I lose the month and year. Any ideas here?

**Comment by jhpyle** [comment]
This is a very annoying new thing with Firefox.  I haven't yet figured out what the issue is.  I blame Firefox, because there was no problem with the old Firefox and it works fine with Chrome.  It probably has to do with an interaction between Firefox, jQuery Validate, and jQuery.

**Comment by jrmiller82** [comment]
Thanks. I'll close this then.

**Comment by jhpyle** [comment]
This is fixed in the latest version.
