### ISSUE TITLE
Visual issue with 'uncheck others'

### ISSUE THREAD

**Issue by CTJoshuaY** [jhpyle/docassemble#129]
Hi,

I'm getting a visual (but not functional) error with uncheck others with the below yaml setup.

Checking either of the 'exclusive' yes no fields while the other is checked correctly changes the true/false value of the answer, but does not update the label bootstrap class to btn-light from btn-primary. Also notably, the 'aria-checked' value does not change to false.

I'm on Chrome v71 for mac.

```
---
question: |

  Demo incorrect css classes on uncheck others

subquestion: |

  This is a demonstration of the uncheck others functionality.

  First, check one of the exclusive options, then check the other.

fields:
  - "Not exclusive": not_exclusive
    datatype: yesnowide
  - "Exclusive One": exclusive_one
    datatype: yesnowide
    uncheck others: [exclusive_two]
  - "Exclusive Two": exclusive_two
    datatype: yesnowide
    uncheck others: [exclusive_one]
continue button field: done
---
Mandatory: True
question: |
  Which did you check?
subquestion: |
  Not exclusive: ${ not_exclusive }

  Exclusive One: ${ exclusive_one }

  Exclusive Two: ${ exclusive_two }

```

**Comment by jhpyle** [comment]
Thanks for letting me know about this.  This should be fixed in 0.4.17.
