### ISSUE TITLE
Documentation: limiting file types on attachments

### ISSUE THREAD

**Issue by jrmiller82** [jhpyle/docassemble#13]
Is this intended?

http://docassemble.org/docs/documents.html#tocAnchor-1-1-6

The code and example don't seem to show limiting anything.

**Comment by jhpyle** [comment]
Sorry!  That was a typo.  Thanks for letting me know.

[Fixed now](http://docassemble.org/docs/documents.html#valid%20formats)

**Comment by jrmiller82** [comment]
Awesome! Thanks!
