### ISSUE TITLE
Gateway Error

### ISSUE THREAD

**Issue by mzaferkucukkurt** [jhpyle/docassemble#134]
Hi!

I've created a form in your program. I don't have problems when I use English characters in form. However, I am having problems when I use Turkish characters. I will be very happy if you help. 

> Gateway Timeout
The gateway did not receive a timely response from the upstream server or application.
Apache/2.4.25 (Debian) Server at 68.183.219.161 Port 80

> Error log:
[Mon Mar 25 16:00:52.138706 2019] [wsgi:error] [pid 15607:tid 140493041055488] obtain_lock: waiting for da: lock: HfZqanIRYfoRQyObMjCtgmQkHoHpZmiv:docassemble.playground1:dilekce.yml
[Mon Mar 25 16:02:41.290849 2019] [wsgi:error] [pid 1038:tid 140492842907392] [client 78.185.104.170:1654] Timeout when reading response headers from daemon process 'docassemble.webserver': /usr/share/docassemble/webapp/docassemble.wsgi, referer: http://68.183.219.161/interview?i=docassemble.playground1%3Adilekce.yml

**Comment by jhpyle** [comment]
A timeout error means that some Python code ran for so long that the web server gave up and terminated the connection.  Does the timeout happen when it is time for the application to generate a document?  Are you generating a document from Markdown?  Or generating a document from DOCX?  Can you share all of the code and document templates with me so that I can try to reproduce it?  In general there should not be a problem with using a Turkish alphabet.  I have seen a lot of problems related to non-English alphabets, but I have not seen a timeout error as a result of a problem with non-English text.  There might be some other issue.

**Comment by mzaferkucukkurt** [comment]
Timeout error occurs when I use the Turkish character in the form. I don't have a problem when I use English characters. My form link is : http://68.183.219.161/interview?i=docassemble.playground1%3Adilekce.yml#page1

---
modules:
	- docassemble.base.util
---
mandatory: True
code: |
	define("Today", today())
---
initial: True
code: |
  import datetime
  import types
  class FalseBoolean(object):
    def primitive_value(self):
      return False
    def is_undefined(self):
      return False
    def __nonzero__(self):
      return False
    def logical_and(self, arg):
      return self
    def logical_or(self, arg):
      if arg.is_undefined():
        return Undefined()
      else:
        return (TrueBoolean() if arg.__nonzero__() else self)
    def logical_not(self):
      return TrueBoolean()
    def logical_equals(self, arg):
      if arg.is_undefined():
        return Undefined()
      else:
        return (self if arg.__nonzero__() else TrueBoolean())
  class TrueBoolean(object):
    def primitive_value(self):
      return True
    def is_undefined(self):
      return False
    def __nonzero__(self):
      return True
    def logical_and(self, arg):
      if arg.is_undefined():
        return Undefined()
      else:
        return (self if arg.__nonzero__() else FalseBoolean())
    def logical_or(self, arg):
      return self
    def logical_not(self):
      return FalseBoolean()
    def logical_equals(self, arg):
      if arg.is_undefined():
        return Undefined()
      else:
        return (self if arg.__nonzero__() else FalseBoolean())
  class Undefined(object):
    def is_undefined(self):
      return True
    def __nonzero__(self):
      return False
    def primitive_value(self):
      return False
    def logical_and(self, arg):
      if arg.is_undefined():
        return self
      else:
        return (self if arg.__nonzero__() else augment(False))
    def logical_or(self, arg):
      if arg.is_undefined():
        return self
      else:
        return (augment(True) if arg.__nonzero__() else self)
    def logical_not(self):
      return self
    def logical_equals(self, arg):
      return self
    def all_true(self):
      return self
    def all_false(self):
      return self
    def any_true(self):
      return self
    def all_false(self):
      return self
    def __add__(self, other):
      return self
    def __mul__(self, other):
      return self
    def __sub__(self, other):
      return self
    def __div__(self, other):
      return self
    def __eq__(self, other):
      return self
    def __lt__(self, other):
      return self
    def __le__(self, other):
      return self
    def __gt__(self, other):
      return self
    def __ge__(self, other):
      return self
    def __ne__(self, other):
      return self
    def __len__(self):
      return self
  class Datetime(datetime.datetime):
    def is_undefined(self):
      return False
    def primitive_value(self):
      return datetime.datetime(self.year, self.month, self.day, self.hour, self.minute, self.second, self.microsecond, self.tzinfo)
    def __eq__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() == other.primitive_value())
    def __lt__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() < other.primitive_value())
    def __le__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() <= other.primitive_value())
    def __gt__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() > other.primitive_value())
    def __ge__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() >= other.primitive_value())
    def __ne__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() != other.primitive_value())
  class Time(datetime.time):
    def is_undefined(self):
      return False
    def primitive_value(self):
      return datetime.time(self.hour, self.minute, self.second, self.microsecond, self.tzinfo)
    def __eq__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() == other.primitive_value())
    def __lt__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() < other.primitive_value())
    def __le__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() <= other.primitive_value())
    def __gt__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() > other.primitive_value())
    def __ge__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() >= other.primitive_value())
    def __ne__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() != other.primitive_value())
  class Float(float):
    def is_undefined(self):
      return False
    def primitive_value(self):
      return float(self)
    def __add__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() + (other.primitive_value()))
    def __mul__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() * (other.primitive_value()))
    def __sub__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() - (other.primitive_value()))
    def __div__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() / (other.primitive_value()))
    def __eq__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() == other.primitive_value())
    def __lt__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() < other.primitive_value())
    def __le__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() <= other.primitive_value())
    def __gt__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() > other.primitive_value())
    def __ge__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() >= other.primitive_value())
    def __ne__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() != other.primitive_value())
  class Integer(int):
    def is_undefined(self):
      return False
    def primitive_value(self):
      return int(self)
    def __add__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() + (other.primitive_value()))
    def __mul__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() * (other.primitive_value()))
    def __sub__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() - (other.primitive_value()))
    def __div__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() / (other.primitive_value()))
    def __eq__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() == other.primitive_value())
    def __lt__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() < other.primitive_value())
    def __le__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() <= other.primitive_value())
    def __gt__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() > other.primitive_value())
    def __ge__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() >= other.primitive_value())
    def __ne__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() != other.primitive_value())
  class String(object):
    def __init__(self, string):
      self.string = string
    def is_undefined(self):
      return False
    def primitive_value(self):
      return self.string
    def __len__(self):
      return Integer(self.primitive_value().__len__())
    def __add__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() + (other.primitive_value()))
    def __eq__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() == (other.primitive_value()))
    def __lt__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() < (other.primitive_value()))
    def __le__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() <= (other.primitive_value()))
    def __gt__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() > (other.primitive_value()))
    def __ge__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() >= (other.primitive_value()))
    def __ne__(self, other):
      if other.is_undefined():
        return other
      else:
        return augment(self.primitive_value() != (other.primitive_value()))
  class Dictionary(object):
    def __init__(self, da_dict):
      self.da_dict = da_dict
    def is_undefined(self):
      return False
    def primitive_value(self):
      return self.da_dict
    def all_true(self):
      return augment(self.da_dict.all_true())
    def all_false(self):
      return augment(self.da_dict.all_false())
    def any_true(self):
      return augment(self.da_dict.any_true())
    def any_false(self):
      return augment(self.da_dict.any_false())
    def __str__(self):
      return unicode(self.da_dict)
  def augment(something):
    string_type = type('a')
    bool_type = type(True)
    integer_type = type(1)
    float_type = type(1.0)
    time_type = type(datetime.time())
    datetime_type = type(datetime.datetime(1, 1, 1))
    my_type = type(something)
    alt_type = something.__class__.__name__
    if(my_type == string_type or alt_type == 'unicode'):
      return String(something)
    elif(my_type == bool_type):
      if(something == True):
        return TrueBoolean()
      else:
        return FalseBoolean()
    elif(my_type == integer_type or alt_type == 'int'):
      return Integer(something)
    elif(my_type == float_type or alt_type == 'float'):
      return Float(something)
    elif(my_type == time_type):
      return Time(something.hour, something.minute, something.second, something.microsecond, something.tzinfo)
    elif(my_type == datetime_type or alt_type == 'DADateTime'):
      return Datetime(something.year, something.month, something.day, something.hour, something.minute, something.second, something.microsecond, something.tzinfo)
    elif(alt_type == 'DADict'):
      return Dictionary(something)
    raise Exception("Couldn't augment because type() is " + unicode(my_type) + " and alt type is " + alt_type + " and argument was " + unicode(something))
  def ternary(condition, true_value, false_value):
    if type(condition) == type(Undefined()):
      return Undefined()
    elif condition:
      return true_value
    else:
      return false_value
---
initial: True
code: |
  import re
  from bs4 import BeautifulSoup
  from markdown import markdown

  def markdown_to_plaintext(markdown_string):
    html = markdown(markdown_string)
    html = re.sub(r'<pre>(.*?)</pre>', ' ', html)
    html = re.sub(r'<code>(.*?)</code >', ' ', html)
    soup = BeautifulSoup(html, "html.parser")
    text = ''.join(soup.findAll(text=True))
    return text
---
mandatory: True
code: |
	def ___define_until_idempotent():
		original_dict = all_variables()
		___define_all()
		if all_variables() != original_dict:
			re_run_logic()
	def ___define_all():
		vars = all_variables()

		if ((not ("___shortcut_2_false" in vars)) and (("variable_1" in vars))):
			define("___shortcut_2_false", ((((augment(variable_1) if ("variable_1" in vars) else Undefined()).logical_equals(augment(False))).primitive_value())))
---
initial: True
code: |
	___define_until_idempotent()
---
code: |
	___shortcut_2_false = (variable_1 == False)
---
mandatory: True
code: |
	def passive_possible_variables():
		return { 'Today': (raw(Today) if defined("Today") else ''), 'ad_unvan': (raw(ad_unvan) if defined("ad_unvan") else ''), 'adres': (raw(adres) if defined("adres") else ''), 'basvuru_sahibinin_talebi': (raw(basvuru_sahibinin_talebi) if defined("basvuru_sahibinin_talebi") else ''), 'e_posta': (raw(e_posta) if defined("e_posta") else ''), 'il_ilce': (raw(il_ilce) if defined("il_ilce") else ''), 'numara': (raw(numara) if defined("numara") else ''), 'sikayet_ad_unvan': (raw(sikayet_ad_unvan) if defined("sikayet_ad_unvan") else ''), 'sikayet_adres': (raw(sikayet_adres) if defined("sikayet_adres") else ''), 'sikayet_faks': (raw(sikayet_faks) if defined("sikayet_faks") else ''), 'sikayet_il_ilce': (raw(sikayet_il_ilce) if defined("sikayet_il_ilce") else ''), 'sikayet_telefon': (raw(sikayet_telefon) if defined("sikayet_telefon") else ''), 'sikayet_vergi': (raw(sikayet_vergi) if defined("sikayet_vergi") else ''), 'tarih': (raw(tarih) if defined("tarih") else ''), 'tckno_vergino': (raw(tckno_vergino) if defined("tckno_vergino") else ''), 'tebligat_adresi': (raw(tebligat_adresi) if defined("tebligat_adresi") else ''), 'tebligat_il_ilce': (raw(tebligat_il_ilce) if defined("tebligat_il_ilce") else ''), 'telefon_numarasi': (raw(telefon_numarasi) if defined("telefon_numarasi") else ''), 'uyusmazlik_bedeli': (raw(uyusmazlik_bedeli) if defined("uyusmazlik_bedeli") else ''), 'uyusmazlik_konusu': (raw(uyusmazlik_konusu) if defined("uyusmazlik_konusu") else ''), 'uyusmazlik_tarihi': (raw(uyusmazlik_tarihi) if defined("uyusmazlik_tarihi") else ''), 'variable_1': (raw(variable_1) if defined("variable_1") else ''), '___shortcut_2_false': (raw(___shortcut_2_false) if defined("___shortcut_2_false") else ''), 'vekil_ad_soyad': (raw(vekil_ad_soyad) if defined("vekil_ad_soyad") else ''), 'vekil_adres': (raw(vekil_adres) if defined("vekil_adres") else ''), 'vekil_eposta': (raw(vekil_eposta) if defined("vekil_eposta") else ''), 'vekil_tc': (raw(vekil_tc) if defined("vekil_tc") else ''), 'vekil_tel': (raw(vekil_tel) if defined("vekil_tel") else ''), 'yetki': (raw(yetki) if defined("yetki") else '') }
---
features:
	debug: False
	inverse navbar: False
---
metadata:
	title: |
		Tüketici Hakem Heyeti Formu
	exit label: |
		Powered by Community.lawyer, a public benefit company
---
mandatory: |
	True
question: ''
subquestion: |
	Tüketici Hakem Heyeti Başvuru Formu - 2019
field: variable_1

under: |
	${()}
---
mandatory: |
	True
question: ''
subquestion: |
	Hangi Tüketici Hakem Heyetine Başvuracaksınız ?
fields:
	- "Hangi Tüketici Hakem Heyetine Başvuracaksınız ?": yetki
		datatype: text
		required: true

under: |
	${()}
---
mandatory: |
	True
question: ''
subquestion: |
	Başvuru Tarihi ve Başvuru Numarası
fields:
	- "Başvuru Tarihi": tarih
		datatype: text
		required: true

	- "Başvuru Numarası": numara
		datatype: text
		required: true

under: |
	${()}
---
mandatory: |
	True
question: ''
subquestion: |
	Başvuru Sahibinin Bilgileri
fields:
	- "T.C. Kimlik Nu - Vergi Nu:": tckno_vergino
		datatype: text
		required: true

	- "Adı-Unvanı": ad_unvan
		datatype: text
		required: true

under: |
	${()}
---
mandatory: |
	True
question: ''
subquestion: |
	Başvuru Sahibinin İletişim Bilgileri
fields:
	- "İl/İlçe": il_ilce
		datatype: text
		required: true

	- "Adresi": adres
		datatype: text
		required: true

	- "Tebligat İl/İlçe": tebligat_il_ilce
		datatype: text
		required: true

	- "Tebligat Adresi": tebligat_adresi
		datatype: text
		required: true

	- "Telefon Numarası": telefon_numarasi
		datatype: text
		required: true

	- "Elektronik Posta": e_posta
		datatype: text
		required: true

under: |
	${()}
---
mandatory: |
	True
question: ''
subquestion: |
	Varsa Başvuru Sahibi Vekili Bilgileri
fields:
	- "T.C. Kimlik Numarası": vekil_tc
		datatype: text
		required: false

	- "Adı ve Soyadı": vekil_ad_soyad
		datatype: text
		required: false

	- "Adresi": vekil_adres
		datatype: text
		required: false

	- "Telefon Numarası": vekil_tel
		datatype: text
		required: false

	- "Elektronik Postası": vekil_eposta
		datatype: text
		required: false

under: |
	${()}
---
mandatory: |
	True
question: ''
subquestion: |
	Şikayet Edilen Bilgileri
fields:
	- "Adı/Unvanı": sikayet_ad_unvan
		datatype: text
		required: true

	- "Vergi Numarası": sikayet_vergi
		datatype: text
		required: true

	- "İl/İlçe": sikayet_il_ilce
		datatype: text
		required: true

	- "Adresi": sikayet_adres
		datatype: text
		required: true

	- "Telefonu": sikayet_telefon
		datatype: text
		required: true

	- "Faksı": sikayet_faks
		datatype: text
		required: true

under: |
	${()}
---
mandatory: |
	True
question: ''
subquestion: |
	Uyuşmazlık Konusuna İlişkin Bilgiler
fields:
	- "Uyuşmazlık Tarihi": uyusmazlik_tarihi
		datatype: text
		required: true

	- "Uyuşmazlık Bedeli": uyusmazlik_bedeli
		datatype: text
		required: true

	- "Uyuşmazlık Konusu": uyusmazlik_konusu
		datatype: text
		required: true

	- "Başvuru Sahibinin Talebi": basvuru_sahibinin_talebi
		datatype: text
		required: true

	- html: |
			<p>Uyuşmazlık bedeli mutlaka Türk Lirası cinsinden belirtilmelidir.</p>


under: |
	${()}
---
mandatory: |
	True
question: ''
subquestion: |
	Formunuzu sistemimiz üzerinden doldurduğunuz için teşekkürler.

attachment code: |
	filter(bool, [___basvuru_formu_pdf_1138_attachment_1296])
allow emailing: False
under: |
	${()}
css: |
  <style>
    button[type='submit'] {
      display: none;
    }
  </style>
---
code: |
	if True:
		import requests
		import json
		import time
		template_id = 1138
		access_key = 'umXK8H62qu'
		drawn_variables = {'35278': markdown_to_plaintext(unicode(yetki if defined("yetki") else "")), '35279': markdown_to_plaintext(unicode(tarih if defined("tarih") else "")), '35282': markdown_to_plaintext(unicode(ad_unvan if defined("ad_unvan") else "")), '35285': markdown_to_plaintext(unicode(tebligat_il_ilce if defined("tebligat_il_ilce") else "")), '35292': markdown_to_plaintext(unicode(vekil_tel if defined("vekil_tel") else "")), '35296': markdown_to_plaintext(unicode(sikayet_il_ilce if defined("sikayet_il_ilce") else "")), '35299': markdown_to_plaintext(unicode(sikayet_faks if defined("sikayet_faks") else "")), '35300': markdown_to_plaintext(unicode(uyusmazlik_tarihi if defined("uyusmazlik_tarihi") else "")), '35286': markdown_to_plaintext(unicode(tebligat_adresi if defined("tebligat_adresi") else "")), '35280': markdown_to_plaintext(unicode(numara if defined("numara") else "")), '35281': markdown_to_plaintext(unicode(tckno_vergino if defined("tckno_vergino") else "")), '35283': markdown_to_plaintext(unicode(il_ilce if defined("il_ilce") else "")), '35284': markdown_to_plaintext(unicode(adres if defined("adres") else "")), '35290': markdown_to_plaintext(unicode(vekil_ad_soyad if defined("vekil_ad_soyad") else "")), '35294': markdown_to_plaintext(unicode(sikayet_ad_unvan if defined("sikayet_ad_unvan") else "")), '35297': markdown_to_plaintext(unicode(sikayet_adres if defined("sikayet_adres") else "")), '35298': markdown_to_plaintext(unicode(sikayet_telefon if defined("sikayet_telefon") else "")), '35287': markdown_to_plaintext(unicode(telefon_numarasi if defined("telefon_numarasi") else "")), '35288': markdown_to_plaintext(unicode(e_posta if defined("e_posta") else "")), '35289': markdown_to_plaintext(unicode(vekil_tc if defined("vekil_tc") else "")), '35291': markdown_to_plaintext(unicode(vekil_adres if defined("vekil_adres") else "")), '35293': markdown_to_plaintext(unicode(vekil_eposta if defined("vekil_eposta") else "")), '35295': markdown_to_plaintext(unicode(sikayet_vergi if defined("sikayet_vergi") else "")), '35301': markdown_to_plaintext(unicode(uyusmazlik_bedeli if defined("uyusmazlik_bedeli") else "")), '35302': markdown_to_plaintext(unicode(uyusmazlik_konusu if defined("uyusmazlik_konusu") else "")), '35303': markdown_to_plaintext(unicode(basvuru_sahibinin_talebi if defined("basvuru_sahibinin_talebi") else ""))}
		post_data = { 'template_id': template_id, 'access_key': access_key, 'drawn_target_variables': drawn_variables }
		fill_response = requests.post('https://community.lawyer/fill', json=post_data).json()
		task_id = fill_response.get('task_id')
		filled_attachment_url = ""
		done = False
		pdf_attempts = 0
		while not done and pdf_attempts < 250:
			task_response = requests.get('https://community.lawyer/tasks?task_id={0}&access_key={1}'.format(task_id, access_key)).json()
			done = task_response.get('status') == 'done'
			filled_attachment_url = task_response.get('document')
			pdf_attempts += 1
			time.sleep(.2)
		___basvuru_formu_pdf_1138_attachment_1296 = DAFileCollection()
		___basvuru_formu_pdf_1138_attachment_1296.pdf = DAFile()
		___basvuru_formu_pdf_1138_attachment_1296.pdf.initialize(extension="pdf")
		if done:
			___basvuru_formu_pdf_1138_attachment_1296.pdf.from_url(filled_attachment_url)
			___basvuru_formu_pdf_1138_attachment_1296.info = {'name': 'basvuru_formu', 'filename': 'basvuru_formu', 'description': ''}
		else:
			___basvuru_formu_pdf_1138_attachment_1296.pdf.from_url('https://community.lawyer/static/blank.pdf')
			___basvuru_formu_pdf_1138_attachment_1296.info = {'name': 'We encountered a problem', 'filename': 'basvuru_formu', 'description': 'There was a problem filling your Pdf - please try again'}
	else:
		___basvuru_formu_pdf_1138_attachment_1296 = ''
---
mandatory: |
	True
question: ''
subquestion: |
	Thank you for using this app. Your session is complete. ${()}
---

**Comment by strangerloops** [comment]
hi @mzaferkucukkurt - looks like this issue is happening because community.lawyer's pdf filling service isn't correctly handling the turkish characters. aiming to have a fix in by the end of the week and will update when it's in. thanks for your patience!

**Comment by mzaferkucukkurt** [comment]
> hi @mzaferkucukkurt - looks like this issue is happening because community.lawyer's pdf filling service isn't correctly handling the turkish characters. aiming to have a fix in by the end of the week and will update when it's in. thanks for your patience!

hi @strangerloops thank you so much everything.
