### ISSUE TITLE
Uploading python package as zip causes "Error of type processing upload: cannot use a string pattern on a bytes-like object" error

### ISSUE THREAD

**Issue by lino** [jhpyle/docassemble#135]
**Steps to reproduce**:
Create a python client with swagger-codegen or possibly any other zip file, select it in the package manager, click the update button.

**Expected behaviour**:
The package should be installed

Can provide zip file on request, if it's a problem with how swagger-codegen creates packages, advice how to do it correctly would be appreciated.

**Comment by jhpyle** [comment]
All that docassemble does with an uploaded zip file is 1) try to extract the name of the Python package from the setup.py file; 2) pass the zip file to `pip` for installation.

One thing you could test is whether you can do `pip install ./myzipfile.zip` on the zip file on an ordinary Python installation.

To figure out what the error is, I would need to see a stack trace (if one was generated) or you could send me the Zip file in a private message on Slack.

**Comment by jhpyle** [comment]
I am closing this for now because I didn't hear anything more, but feel free to reopen and provide more information about the zip file you were using if this continues to be an issue.
