### ISSUE TITLE
Custom example questions

### ISSUE THREAD

**Issue by klt-drafthouse** [jhpyle/docassemble#136]
Is there a way to add custom examples blocks?  I can see them in the data/questions/examples folder - but what is the best way to edit / add to that if I am running docassemble from a docker container?  Can it be done while using docker deployment - or am I looking at editing the source code and installing / running that way?

**Comment by jhpyle** [comment]
The examples are listed in this file:
https://github.com/jhpyle/docassemble/blob/master/docassemble_base/docassemble/base/data/questions/example-list.yml
and all of the referenced mini-interviews are in this folder:
https://github.com/jhpyle/docassemble/tree/master/docassemble_base/docassemble/base/data/questions/examples
This is customizable if you want to fork the core packages; there is no feature for user customization of the example interviews, although I could make it customizable if you want.

**Comment by klt-drafthouse** [comment]
It would be a nice-to-have.  At the moment to train people I refer them out to examples and practice items in a github repository I am building, but would be neater to have it in the playground.  Probably good for them to grab the examples from github and put them in, rather than being spoon-fed too much...

**Comment by jhpyle** [comment]
Check out the `playground examples` directive in the Configuration: https://docassemble.org/docs/config.html#playground%20examples

**Comment by jhpyle** [comment]
I am closing this because I added a feature in 0.4.38 for the issue (`playground examples`), but feel free to reopen if that doesn't suffice.
