### ISSUE TITLE
Translate portuguese

### ISSUE THREAD

**Issue by Hamudss** [jhpyle/docassemble#139]
I have a translate document for Brazil Portuguese of the words the system use. Do you can insert in system and put on at a new version?

**Comment by jhpyle** [comment]
Yes, you can call it `pt-words.yml` and put it here:
https://github.com/jhpyle/docassemble/tree/master/docassemble_base/docassemble/base/data/sources
and submit it with a pull request.

Or, if you aren't familiar with making pull requests, you could upload it here and I can add it.

**Comment by Hamudss** [comment]
Solved

**Comment by Hamudss** [comment]
Can you also update the docker image?

**Comment by jhpyle** [comment]
The Docker image starts updating as soon as a new version is published on GitHub, but it takes about 40 minutes to finish building.
