### ISSUE TITLE
Documentation: Need further explanation on the resume button in review blocks

### ISSUE THREAD

**Issue by jrmiller82** [jhpyle/docassemble#14]
http://docassemble.org/docs/fields.html#tocAnchor-1-19-2

You give instruction on how to change the label of the resume block; but, in my attempts to play with it, clicking the resume button does nothing and leaves me stuck on the review page despite one or more yet-to-be-asked mandatory question blocks. Can the docs explain more of what's going on?

**Comment by jrmiller82** [comment]
(Sorry for all the issues; just think this project has a lot of promise!)

**Comment by jhpyle** [comment]
In your interview, how exactly does the user get to the review block?  The review screen is designed to be shown through an [action](http://docassemble.org/docs/functions.html#actions), meaning that it is separate from the underlying logical path of the interview. The Resume button on a review screen is like a [`continue`](http://docassemble.org/docs/questions.html#special%20buttons) special button; it has the effect of "we now return to our regularly scheduled programming."  If your review screen _is_ the regularly scheduled programming, clicking Resume will have no effect.

In any case, I will make the documentation more clear.

**Comment by jrmiller82** [comment]
Thank you. I was using it under an event. I will try moving it to the menu instead when I have some tinkering time.

**Comment by jrmiller82** [comment]
Got it working under the upper-right menu. Thanks!

Is there a way to also trigger that from a button? I.e. make a button in an interview question trigger the review answers event without making it part of the regularly scheduled programming? I'm thinking about maybe people who wouldn't know to use the menu, but may follow a big "review your answsers" button in a question, just before final submission of an intake form or something of that nature.

**Comment by jhpyle** [comment]
I believe this issue has been addressed, so I am closing it.
