### ISSUE TITLE
 Problem with installing new package

### ISSUE THREAD

**Issue by Hamudss** [jhpyle/docassemble#144]
When I generate a new package, it gets stuck in the installation message, and it does not leave the screen, however if I access the package manager it shows my package installed.

**Comment by jhpyle** [comment]
It can take a long time for `pip` to finish what it is doing.  In addition to updating the package in question, it also updates other packages.  Eventually the screen should move past "Please wait. Packages are updating." and update with a final status.  More information about what is happening is available in the `worker.log`.  If there is an error with `pip`, the `worker.log` might contain information about what that error is.  Without more information I can't tell what the issue might be.

**Comment by knod** [comment]
I'm sure your todo list is long, but if you ever have time to come up for air (and if it's possible) an installation progress bar may help folks waiting for completion.

**Comment by knod** [comment]
If you point me to the script where a message can be added, I can attempt to make a PR with a message added in.

**Comment by jhpyle** [comment]
The message has been added.
