### ISSUE TITLE
Documentation: Is there a way to mix-mash buttons

### ISSUE THREAD

**Issue by jrmiller82** [jhpyle/docassemble#15]
In playing around, I can't seem to get buttons that mix with exit, restart etc., with buttons that set a field.

For example: 

```
---
button:
  - Exit: exit
  - Restart: restart
---
```
Works just fine. But if you try and mix it with a field, the exit and restart no longer works because it's been assigned to the field. For example: 

```
field: bvar
button:
  - Exit: exit
  - Restart: restart
  - More: True
---
```
No longer gives you the exit and restart functionality. Is there a way to mix these? 

If I do:
```
---
buttons
  - Exit: exit
  - Restart: restart
  - Continue: continue
---
```
I get a blank screen with just a second continue button and that doesn't look very professionl and is what I'm trying to avoid with the Continue button.

**Comment by jhpyle** [comment]
I should have said in the documentation that if you add `field` to a question with "special" buttons (exit, restart, etc.), then **docassemble** will treat it as a regular multiple choice question.

I added a [documentation section](http://docassemble.org/docs/questions.html#special%20mixed) that explains how to mix buttons that exit the interview with buttons that set a variable.

**Comment by jrmiller82** [comment]
Awesome. Thank you. The use buttons to run code is perfect.
