### ISSUE TITLE
Login stopped working + missing access.log

### ISSUE THREAD

**Issue by bennlich** [jhpyle/docassemble#162]
I have a docassemble instance that appears to be running normally:
```
supervisorctl status
apache2                          RUNNING   pid 1406, uptime 24 days, 1:54:51
celery                           RUNNING   pid 2397, uptime 24 days, 1:50:02
cron                             RUNNING   pid 1528, uptime 24 days, 1:54:34
exim4                            RUNNING   pid 1538, uptime 24 days, 1:54:33
initialize                       RUNNING   pid 9, uptime 24 days, 1:56:48
postgres                         RUNNING   pid 555, uptime 24 days, 1:56:16
rabbitmq                         RUNNING   pid 2188, uptime 24 days, 1:50:03
redis                            RUNNING   pid 715, uptime 24 days, 1:55:41
reset                            EXITED    Jun 07 11:02 PM
sync                             STOPPED   Not started
syslogng                         STOPPED   Not started
update                           STOPPED   Not started
watchdog                         RUNNING   pid 8, uptime 24 days, 1:56:48
websockets                       RUNNING   pid 2423, uptime 24 days, 1:49:55
```

The default interview also works as expected.

However there are two strange things:
1) I have no apache `access.log` files in `/usr/share/docassemble/log`.
2) I can no longer log in.
a) When I log in with a bogus username/password, I see the `Incorrect Password` error that I expect.
b) When I log in with a good username and bad password, nothing happens.
c) When I log in with a good username and good password, nothing happens.

I do have some peculiar apache error logs in `/var/log/apache2/`:

```
tail /var/log/apache2/error.log.1
[Sun Jun 30 06:28:41.956057 2019] [mpm_event:notice] [pid 1444:tid 139637613498432] AH00493: SIGUSR1 received.  Doing graceful restart

tail /var/log/apache2/error.log  
[Sun Jun 30 06:28:44.966753 2019] [mpm_event:notice] [pid 1444:tid 139637613498432] AH00489: Apache/2.4.25 (Debian) mod_wsgi/4.5.11 Python/3.5 configured -- resuming normal operations
[Sun Jun 30 06:28:44.966841 2019] [core:notice] [pid 1444:tid 139637613498432] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
[Sun Jun 30 11:11:32.112943 2019] [wsgi:error] [pid 86019:tid 139637454497536] [remote 52.7.141.1:34088] index: there was an exception EOFError: Ran out of input after fetch_user_dict with U8OVZT4K56YIE0C8Q3AC2GFEZGRIER39 and docassemble.jcc.abilitytopay:data/questions/interview.yml, so we need to reset
```

I'm running docassemble 0.4.41.

Anything else I oughta look at before I reboot?

**Comment by jhpyle** [comment]
Is there an error in `docassemble.log`?  In the JavaScript console?

**Comment by jhpyle** [comment]
I haven't seen anything like this before, but you might try closing your browser, then navigating directly to `/interviews` on your server, and try logging in when the login screen comes up.  The error you saw is related to resuming an interview session, which it might be trying to do immediately after logging in.  That error message you saw is caused by corruption to the interview answers for a given session, which can happen if there is an error at the wrong time.  If you can log in and then delete the interview sessions associated with the account, maybe the problem will go away.

**Comment by bennlich** [comment]
> Is there an error in docassemble.log? In the JavaScript console, under the Network tab, in the Response of a request that ended in a 501?

Nope. Nothing in `docassemble.log` or `docassemble.log.1` that correspond to my login attempts, and no javascript errors or network errors. I'm going to DM you a video of me trying to log in in case that sheds any light.

I did find these in docassemble.log.1. They don't seem related to the logins, but I don't know what to make of the paths (ip address redacted):
```
docassemble: ip=xxx i=docassemble.jcc.abilitytopay:data/questions/interview.yml//CHANGELOG.txt uid=LIB4X1CQDO8DYN45NL6UZZYEO4IAU3FV user=anonymous 2019-07-02 04:39:33 YAML file docassemble.jcc.abilitytopay:data/questions/interview.yml//CHANGELOG.txt not found
docassemble: ip=xxx i=docassemble.jcc.abilitytopay:data/questions/interview.yml//README.txt uid=8MEHCP3M1P38R7NI1DP627HJO5EX7RLK user=anonymous 2019-07-02 04:39:33 YAML file docassemble.jcc.abilitytopay:data/questions/interview.yml//README.txt not found
docassemble: ip=xxx i=docassemble.jcc.abilitytopay:data/questions/interview.yml//readme.html uid=C75VEX33RKAK7U1V4SA718O8GIHUJCUC user=anonymous 2019-07-02 04:39:34 YAML file docassemble.jcc.abilitytopay:data/questions/interview.yml//readme.html not found
docassemble: ip=xxx i=docassemble.jcc.abilitytopay:data/questions/interview.yml//readme.html uid=GPFYGPW2UQKVRGRJP6J59I3ZK4WLTHTH user=anonymous 2019-07-02 04:39:35 YAML file docassemble.jcc.abilitytopay:data/questions/interview.yml//readme.html not found
docassemble: ip=xxx i=docassemble.jcc.abilitytopay:data/questions/interview.yml//license.txt uid=4V9XCGVB0BJUN4BX70FE9U523RULTIDU user=anonymous 2019-07-02 04:39:36 YAML file docassemble.jcc.abilitytopay:data/questions/interview.yml//license.txt not found
```

**Comment by jhpyle** [comment]
Are you out of hard drive space on the server, by any chance?  The output of `df -h` when you are inside the Docker container would indicate whether that is true.

The `access.log` file is in `/var/log/apache2`, not in `/usr/share/docassemble/log`.

The errors in `docassemble.log.1` are consistent with a user visiting URLs like:

`https://mycitations.uat.courts.ca.gov/interview?i=docassemble.jcc.abilitytopay:data/questions/interview.yml//CHANGELOG.txt`

So those messages seem harmless.

I can't reproduce the behavior you are seeing when I try logging into my own sites.  I get "Incorrect Password" as an error.

**Comment by bennlich** [comment]
Doh. Of course. This was an "I forgot my login info" bug. Sorry for the wild goose chase.

Maybe there should be an "incorrect username/pass" error message even when you try to log in with a non-existent usernames? That was part of what made me think something was up.

**Comment by jhpyle** [comment]
I am glad you were able to get in, but I still think something is up.  When I log in to my server and use a wrong password or a non-existent account, I get an appropriate error message.  But those messages weren't coming up on your site when I was testing it last night.  Could you tell me the version numbers of Flask, Flask-Login, and Flask-User?  They are listed on the Package Management (`/updatepackage`) page.

**Comment by bennlich** [comment]
Flask 1.0.2
Flask-Login 0.4.1
Flask-User 0.6.21

**Comment by bennlich** [comment]
> The access.log file is in /var/log/apache2, not in /usr/share/docassemble/log.

Ah, interesting. Has this always been the case? I have another docassemble instance with the following:

```
$ ls /usr/share/docassemble/log
access.log
access.log.1
access.log.2
access.log.3
access.log.4
docassemble-log.conf
docassemble.log
docassemble.log.1
docassemble.log.2
docassemble.log.3
docassemble.log.4
docassemble.log.5
docassemble.log.6
docassemble.log.7
error.log
error.log.1
error.log.2
error.log.3
error.log.4
other_vhosts_access.log
worker.log
worker.log.1
worker.log.2
worker.log.3
worker.log.4
worker.log.5
worker.log.6
worker.log.7
```

**Comment by jhpyle** [comment]
When you visit Logs in the web interface, the Apache log files are copied to `/usr/share/docassemble/log/`, but the original (and up-to-date) files are in `/var/log/apache2`.

**Comment by bennlich** [comment]
@jhpyle Aha. That explains it.

When docassemble backs up logs, does it backup `/var/log/apache2`, or just `/usr/share/docassemble/log/` ?

**Comment by jhpyle** [comment]
Only the files under `/usr/share/docassemble/log/` get copied to the S3 bucket for backup.

**Comment by bennlich** [comment]
> When you visit Logs in the web interface, the Apache log files are copied to /usr/share/docassemble/log/, but the original (and up-to-date) files are in /var/log/apache2.

> Only the files under /usr/share/docassemble/log/ get copied to the S3 bucket for backup.

I see. I think one ramification of this is that my backups in `/usr/share/docassemble/backup` can get pretty bloated, but only if I've visited the logs tab in the admin UI.

I have some pretty hefty apache access.log files (currently split across 8 files, each between 20MB and 100MB). The 100MB log made it into `/usr/share/docassemble/log`, so now every nightly backup includes that huge log.

I don't think there's a change to be made in docassemble--I'm just thinking out loud here. Probably the solution is for me to allocate enough disk space to my VM to that it can hold a week's worth of 100MB apache logs and 300MB DB backups (worst-case-scenario). (Currently it has 30GB of space, which is not quite enough.)

FWIW, it was rather confusing to find these large apache logs in `/usr/share/docassemble/log` on one deployment and not on another. I understand the behavior now though.
