### ISSUE TITLE
No field validation for user input

### ISSUE THREAD

**Issue by combinatorist** [jhpyle/docassemble#163]
At least in the demonstration Interview, it seemed I could enter any combination of characters in any field (e.g. letters and punctuation in the SSN).

Obviously, there's no way for DocAssemble to know what's valid on its own, but it would be good for advanced users to be able to add regex and for a couple common restrictions to be available to other users via YAML (e.g. "no-spaces", "no-numbers", etc).

**Comment by michaelhofrichterHVL** [comment]
There's some -- see https://docassemble.org/docs/fields.html#min

**Comment by jhpyle** [comment]
Yes, that is the relevant section of the documentation; scroll down to the part that discusses the `validate` field modifier.  You can use Python code to write your own input validation functions.

If you want to extend the JavaScript input validation, see the documentation for the [jQuery Validation Plugin](https://jqueryvalidation.org/).  It has an API.  But it is probably easier to do validation of user input using server-side code with `validate` or `validation code`.

**Comment by combinatorist** [comment]
Ok, thanks, @michaelhofrichterHVL and @jhpyle. I figured there would be. Again, like #164 I think this is a limitation of someone else's deployment I was playing with.

Closing now, but feel free to reopen if you like.
