### ISSUE TITLE
Hard to return to main menu

### ISSUE THREAD

**Issue by combinatorist** [jhpyle/docassemble#164]
It was not intuitive for me to do site navigation via the link to my sign-in, but that after some looking, that's the only way I could find to get to "Available Interviews". It may be harder for some and easier to others - just reporting my experience.

**Comment by jhpyle** [comment]
"Available Interviews" is a page of the web site at `/list`.  It is not available in the docassemble menu by default, but you can add it to the menu using the [`show dispatch link`](https://docassemble.org/docs/config.html#show%20dispatch%20link) Configuration directive.

The URL to "Available Interviews" can be generated with a call to `url_of('dispatch')`.

**Comment by combinatorist** [comment]
Ok, thanks for the help, @jhpyle!

It sounds like it's perfectly configurable. I was looking at someone's working deployment before getting deep into trying it myself, so I won't assume that DocAssemble is limited to their particular configuration.

I don't know your policy on this, but this ticket is resolved from my perspective. I'm going to close it, but of course you can reopen if it's useful to you.
