### ISSUE TITLE
API doesn't progress when non-required variables are null

### ISSUE THREAD

**Issue by konstantinbrazhnik** [jhpyle/docassemble#169]
### Description
When a `required: False` variable is left blank, but used later on in the interview (usually with the expectation that it will render a blank space), the Docassemble interview will intelligently keep moving forward with the interview.

However, if you run the [Set Variables](https://docassemble.org/docs/api.html#session_post) method in the API, the interview will not progress in either the returned question data or via a new call to the [Get Current Question](https://docassemble.org/docs/api.html#session_question) method.

While the workaround is to utilize a `if ( defined('unrequired1') ):` block to explicitly not use the unrequired variable unless it is defined, this is burdensome and seems like the front-end application has already been updated for this to not be an issue.

The Yaml file below illustrates this.  To replicate the bug:

1. Initiate a new session via the API
2. Set the `required1` and `required2` variables via the API

Notice that the response is not the next question, but the same question even though all `required` fields have been set.

### Yaml Interview File

```
metadata:
  title: Required Field API Behaviour
  short title: required_field_bug
---
question: |
  # Required / Unrequired Fields Bug
subquestion: |
  This question has both required and unrequired fields.
  
  Fill out the required fields and ignore the others.
fields:
  - Required Field 1: required1
    hint: Fill this in...
    required: True
  - Unrequired Field 1: unrequired1
    hint: Leave this blank...
    required: False
  - Required Field 2: required2
    hint: Fill this in...
    required: True
  - Unrequired Field 2: unrequired2
    hint: Leave this blank...
    required: False
---
mandatory: True
question: |
  # Results
subquestion: |
  The value of Required Field 1 is ${required1}.  
  The value of Required Field 2 is ${required2}.
  
  The value of Unrequired Field 1 is ${unrequired1}.  
  The value of Unrequired Field 2 is ${unrequired2}.
  
  ## The Bug
  
  Run this same interview via the API and submit values for required1 and required2.
  
  The interview does not progress because it will not accept an undefined value for a "required" field.
  
  While the workaround is to use the defined('unrequired1') function, 
  the front end of DA has obviously figured out how deal with this so the API should as well.
sets: all_done

```

**Comment by jhpyle** [comment]
The API is not intended to be a tool for automating the front end Q&A process, although it has some endpoints that facilitate such a purpose if that is something you want to do.  The `/api/session` POST endpoint can be used to set any variable in the interview, whether that variable is responsive to a given `question` or not.  The `/api/session` POST endpoint bypasses all of the input validation and show/hide logic that is applied when a `question` appears in the web browser and the values are sent to the server.  It is a low-level, raw, do-it-yourself, at-your-own-risk, direct-to-the-Python-namespace interface.

In your code that calls the API, you can look at the current question and see that some of the fields in that question are not required, and then you can set those variables to the empty string or some other null value.

**Comment by konstantinbrazhnik** [comment]
This makes sense to me. Thank you. Closing!
