### ISSUE TITLE
log w/o removing newlines

### ISSUE THREAD

**Issue by bennlich** [jhpyle/docassemble#170]
I'd love to write logs without stripping out newlines (e.g. when logging full tracebacks). Is it safe to set my own logger somewhere in my docassemble package with `logger.set_logmessage(my_new_log_fn)` ?

**Comment by jhpyle** [comment]
I have no idea, but you can try it and see.  `docassemble.webapp.server` uses Python's `logging` package and directs log messages either to syslog (if a syslog server is set up) or to the `docassemble.log` file.  The function that is used throughout docassemble to write to the `docassemble.log` file can be configured by calling `docassemble.base.logger.set_logmessage(my_func)` where `my_func` is some function that takes a log message as an argument.

**Comment by bennlich** [comment]
Thanks. I got what I wanted with the following:

```
import time
import logging
import docassemble.base.logger

sys_logger = logging.getLogger('docassemble')

def log_message_with_timestamp(message):
    sys_logger.debug(time.strftime("%Y-%m-%d %H:%M:%S") + " " + message)

# Override the default docassemble logger
docassemble.base.logger.set_logmessage(log_message_with_timestamp)
```

I just had to be sure to declare my exports with __all__ or DA would try to pickle some unpicklable things.
