### ISSUE TITLE
yesnoradio does not take you to the required field during validation

### ISSUE THREAD

**Issue by JCCChris** [jhpyle/docassemble#175]
The validation should take you to the spot where you need to fill in a value.  Seems to be unique to datatype: yesnoradio

**Comment by jhpyle** [comment]
By "take you to the spot," do you mean scroll the screen?

**Comment by JCCChris** [comment]
Yes

**Comment by jhpyle** [comment]
I made a change in 0.4.70; let me know if it doesn't work.
