### ISSUE TITLE
Feature Request: Dispatch List in the Menu List

### ISSUE THREAD

**Issue by michaelhofrichterHVL** [jhpyle/docassemble#176]
Where there's a dispatch list in the config file, can a link to the url\list be included in the top right drop-down menu?

**Comment by jhpyle** [comment]
Is this the feature you are describing?
https://docassemble.org/docs/config.html#show%20dispatch%20link

**Comment by michaelhofrichterHVL** [comment]
Yes. I feel like I've read through the config documentation multiple times and keep learning new things each time. Thanks for sharing the link.
