### ISSUE TITLE
Feature Request: Delete all pending interviews

### ISSUE THREAD

**Issue by jrmiller82** [jhpyle/docassemble#18]
In testing and learning the application I've accrued something like 300 pending interviews in the `Resume an interview` screen. Is there an easy way to wipe these? Perhaps a button to delete them all? Or is this something already taken care of by one of the cron jobs and I'm worrying over nothing?

**Comment by jhpyle** [comment]
This has been added.  There is now a "Delete All" button on the interview page.

**Comment by jrmiller82** [comment]
Awesome!
