### ISSUE TITLE
Error when image is placed in header of docx template

### ISSUE THREAD

**Issue by swardenaar** [jhpyle/docassemble#181]
Placing an image (both a DAFile from url and a DAStaticFile from a local image) in the header of a docx template causes the following error during document generation:

 File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/docxtpl/__init__.py", line 238, in get_headers_footers_xml
    for relKey, val in self.docx._part._rels.items():
RuntimeError: dictionary changed size during iteration

**Comment by jhpyle** [comment]
I added a line to the documentation to explain that images cannot be added to headers and footers.  This is because of a limitation in `docxtpl`.  See https://docxtpl.readthedocs.io/en/latest/#replace-docx-pictures
