### ISSUE TITLE
Default user name and password for docker version not working?

### ISSUE THREAD

**Issue by weisisheng** [jhpyle/docassemble#185]
Hmm...trying the latest image on localhost:8080, can not login based on instructions... TIA.

admin@admin.com/password

**Comment by jhpyle** [comment]
I can't reproduce the problem.  I created a new server and logged in with the default credentials and it asked me to change the password.

Did you change the admin password in the configuration, maybe?  Are you reusing a docker volume/S3 bucket/Azure Blob Storage from a previous server?

**Comment by weisisheng** [comment]
So strange.  I am using the simplest setup possible having pulled the latest image on to my laptop.  Ubuntu 19.04, Docker 18.09.05.  I had a legacy image from 3 months back.  Deleted everything (containers and images) and repulled with no login success.  I have a modest amount of docker experience having worked with it the last few years.  No other mods (yet).

Will keep at it.  Thanks for quick response!

**Comment by weisisheng** [comment]
Figured it out.  Another app using 8080.  For some reason, localhost:80 wasn't working last night so I thought 8080.  But that was blocked.  Never mind!
