### ISSUE TITLE
Progress value not updated/passed along in API calls

### ISSUE THREAD

**Issue by konstantinbrazhnik** [jhpyle/docassemble#188]
When a question is fetched, the progress value is not passed along. Since this is essentially metadata attached to the question, this would be useful to have to be able to give user feedback on the progress of a particular interview at a glance.

**Comment by jhpyle** [comment]
In 0.4.80 I added `progress` to the JSON representation of the question.  Thanks.

**Comment by konstantinbrazhnik** [comment]
It shows up and works in the JSON representation of the question when you append `json=1` to the url, but if you call the API directly, the progress property stays at `0` for me.

Shouldn't these two functionalities be identical?

**Comment by jhpyle** [comment]
I believe what you're seeing is that making an API call that changes the session variables doesn't advance the progress meter (which is the value of a variable in the interview answers).  But I could change it so that it does advance the progress meter under some circumstances.
