### ISSUE TITLE
Checkboxes minimum is not shown as corrected when the user chooses the minimum amount

### ISSUE THREAD

**Issue by JCCChris** [jhpyle/docassemble#189]
If I set a minimum of 2 checkboxes to be chosen,  the user interface still shows as highlighted in red when the user chooses 2 checkboxes to correct the condition.  

This is different from other errors.  When I fill in a single character for a required text field, the user interface removes the red highlighting to indicate that the error has been corrected.

**Comment by jhpyle** [comment]
This was fixed.
