### ISSUE TITLE
Bug: when uploading yml in playground

### ISSUE THREAD

**Issue by jrmiller82** [jhpyle/docassemble#19]
I'm getting this error using the upload feature in playground: 

```
Error

    AttributeError: 'list' object has no attribute 'from_source'

Log

Traceback (most recent call last):
  File "/usr/share/docassemble/local/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/share/docassemble/local/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/share/docassemble/local/local/lib/python2.7/site-packages/flask_user/decorators.py", line 29, in decorated_view
    return func(*args, **kwargs)
  File "/usr/share/docassemble/local/local/lib/python2.7/site-packages/flask_user/decorators.py", line 76, in decorated_view
    return func(*args, **kwargs)
  File "/usr/share/docassemble/local/local/lib/python2.7/site-packages/docassemble/webapp/server.py", line 7414, in playground_page
    variables_html, vocab_list = get_vars_in_use(interview, interview_status, debug_mode=debug_mode)
  File "/usr/share/docassemble/local/local/lib/python2.7/site-packages/docassemble/webapp/server.py", line 1593, in get_vars_in_use
    field_origins[val].add(interview.questions[val][lang].from_source)
AttributeError: 'list' object has no attribute 'from_source'

```

**Comment by jhpyle** [comment]
Thanks!  And sorry about the error.  I am surprised I never came across that before.  Anyway, I believe I have fixed this in the latest version, which Docker Hub is building right now.  (It should be ready in about an hour).

In case you're interested, this weekend I added capability for interviews to [receive e-mails](http://docassemble.org/docs/background.html#email) from users.  I haven't fully documented it yet, but there is a working example.

**Comment by jrmiller82** [comment]
No worries about errors! I've never written even a shell script that didn't have bugs to squash. :) 

I'll pull the new version tomorrow and test it out. 

What's your planned use case for receiving emails from the users?

**Comment by jhpyle** [comment]
For example, the interview could send out an e-mail to a lawyer, saying "will you agree to accept service in xyz case?"  The e-mail would look like is is coming from "John Smith," but it is actually coming from "John Smith <ghujur@docassemble.example.com>" so any reply will go into the interview where it can be parsed automatically or manually and then the legal documents could be assembled differently depending on the response.  Another example could be a domestic relations case where the interview would handle the plaintiff's correspondence with the defendant, and all replies would be stored in the interview where they could be used as evidence later.  Or a more mundane example, suppose the client is filling out the interview on her computer but has photographs on her phone that are evidence.  It's hard to transfer pictures from a phone to a computer.  This feature would allow her to e-mail the pictures to the interview.

**Comment by jrmiller82** [comment]
Thanks for the detailed replies. Sounds great!

**Comment by jhpyle** [comment]
I believe this issue has been addressed, so I am closing it.
