### ISSUE TITLE
Reuse text paragraph across documents

### ISSUE THREAD

**Issue by marjdk** [jhpyle/docassemble#194]
I would be wonderful to be able to use text paragraphs across documents, without the need to hardcode into the YAML file

**Comment by jhpyle** [comment]
You can use a `template` block that points to a `content file` in Markdown format located in the same package or a different package.  https://docassemble.org/docs/initial.html#template 

When using .docx files for document assembly, you can use `include_docx_template()` to include paragraphs from a separate .docx file.

Where do you want to write the text paragraphs?

**Comment by jhpyle** [comment]
Other features that might be useful are:

* Passing variables to a `template` using `.show()`.
* When using `docx template file`, you can declare a Jinja2 "macro" and then call that macro as a function in your .docx file.  https://jinja.palletsprojects.com/en/2.10.x/templates/#macros
