### ISSUE TITLE
Unicode characters in vocabulary terms

### ISSUE THREAD

**Issue by patenteu** [jhpyle/docassemble#20]
There seems to be a problem with Unicode characters in the pop-up text of vocabulary terms. In this short example, when I click over the accent term of the question, the pop-up message shows the Unicode character instead of the "é" characters. The "résumé" word is displayed as " r\u00e9sum\u00e9".

Forcing default language to french doesn't help. I'm using a docassemble docker image built approximately 3 weeks ago.

Otherwize, docassemble is working great. I began using it for diagnostic purpose of electrical equipment.

Below is an example yaml file that reproduce the described behavior.

```
---
default language: fr
---
terms:
  accent: |
    Accents such as résumé are used in foreign language.
---
question: |
  Do you see correctly the accent over the letter e that should appear as é 
  in the term pop-up.
yesno: accent
mandatory: true
---
```

**Comment by jhpyle** [comment]
Thanks!  I believe I have fixed this in the [latest commit](https://github.com/jhpyle/docassemble/commit/3772320cfa558739895d4822e1550c9874486f68), which Docker Hub is currently processing (should be ready in about an hour).  Your example code was a big help.

**Comment by patenteu** [comment]
I confirm that it works correctly, at least with most common French accentuated characters. 
Thanks a lot for the correction!
