### ISSUE TITLE
Typo in s4cmd option

### ISSUE THREAD

**Issue by houfu** [jhpyle/docassemble#201]
While going through my supervisor initialize error logs, I noticed several of the following errors:

```bash
s4cmd: error: no such option: --endpoint_url
Usage: s4cmd [options]
```

Looking at the docs of [s4cmd](https://github.com/bloomreach/s4cmd#--endpoint-url), it appears that the correct syntax is `--endpoint-url`. The reference to `--endpoint_url` appears to be [here in the code](https://github.com/jhpyle/docassemble/blob/7822956c617e70365f3818290d7f4671d2376711/Docker/initialize.sh#L123) (and perhaps several other places too). 

A bit of background: My docassemble setup uses a S3 compatible object storage from vultr.com. It works fine until I add a `bootstrap theme` configuration option with a custom bootstrap css, which then causes the application to return HTTP Error 500 and become completely unusable (which was when I started studying my logs). I suspect my original problem is unrelated to this typo, but I am also not sure why it would work the first time if there was a typo.

**Comment by jhpyle** [comment]
This should have been fixed in 0.5.20, but let me know if you see s4cmd errors in the initialize logs after upgrading.  Sorry about this, by the way; I added the feature for `endpoint url` several weeks ago but didn't have any way of testing it, so naturally, it didn't work.
