### ISSUE TITLE
Easy way to copy entire contents of all the logs at once

### ISSUE THREAD

**Issue by knod** [jhpyle/docassemble#202]
Instead of dragging the mouse down a long log. cmd+a selects the whole page.

**Comment by knod** [comment]
Maybe include an easy way to copy their filenames too.

**Comment by knod** [comment]
And/or an easy way to download the contents of all the logs at once.

**Comment by knod** [comment]
I see now that you can download one log at a time. That's still a little different than either of those requests, but if you want, I'll drop the 'copy the contents' one in favor of the 'download them all at once one'.

**Comment by jhpyle** [comment]
In 0.5.29 there is an option to download all the log files at once.
