### ISSUE TITLE
POSTURLROOT configuration option only works when DAWEBSERVER=apache

### ISSUE THREAD

**Issue by staffanm** [jhpyle/docassemble#206]
Hi, first of all thank you so much for this incredibly featureful and well documented application!

I've been trying to install docassemble with docker, but running from a sub-location (eg `http://example.org/da/`). The documentation suggests to use `--env POSTURLROOT=/da/` to achieve this. However, when running docker with the default web server (nginx) this option only seem to affect `config.yml`, not the web server configuration, so the actual application is only available from the web server root. However, if I also use `--env DAWEBSERVER=apache` everything works as expected.

It seems that the generated apache config file is affected by the `POSTURLROOT` setting to mount the WSGI app at the correct point, while the corresponding generated nginx config file is not, if I'm reading `Docker/initialize.sh` correctly.

**Comment by staffanm** [comment]
Thank you! That was incredibly fast!

**Comment by jhpyle** [comment]
The previous fix did not actually fix the problem.  Try 0.5.28 instead.

**Comment by jhpyle** [comment]
I think this was fixed, so I am closing this for now.
