### ISSUE TITLE
Adjust `labels above fields` DOM structure to match default DOM structure

### ISSUE THREAD

**Issue by knod** [jhpyle/docassemble#208]
When my interview has `labels above fields: True`, the DOM structure changes, which changes how the style selectors are working. Specifically in my case, the email input.

## Without `labels above fields: True`:
``` html
<div class="form-group row da-field-container da-field-container-datatype-email">
  <label for="YXRjaF9lbWFpbF9hZGRyZXNz" class="col-md-4 col-form-label da-form-label datext-right">E-mail</label>
  <div class="col-md-8 dafieldpart">
    <input value="lsquery@example.com" alt="Input box" class="form-control" type="email" name="YXRjaF9lbWFpbF9hZGRyZXNz" id="YXRjaF9lbWFpbF9hZGRyZXNz" aria-invalid="false">
  </div>
</div>
```

## With `labels above fields: True`:
``` html
<div class="form-group da-field-container da-field-container-datatype-email">
  <label class="da-top-label" for="YXRjaF9lbWFpbF9hZGRyZXNz">E-mail</label>
  <input value="lsquery@example.com" alt="Input box" class="form-control" type="email" name="YXRjaF9lbWFpbF9hZGRyZXNz" id="YXRjaF9lbWFpbF9hZGRyZXNz" aria-invalid="false">
</div>
```

With the default, adjusting the layout means styling the the `.dafieldpart` node. With the feature set to `True`, the `input` node itself needs the styling.

Is this kind of change possible or is it too deep?

**Comment by knod** [comment]
It could also be done the other way around.

**Comment by knod** [comment]
Thanks, this is a great start! Also, I apologize that this disrupts the CSS of already existing projects. I figured better now than later.

If it helps, I noticed a discrepancy between the two. Labels beside fields has `position: relative` set on the `.dafieldpart` node. It comes from the bootstrap `.col-md-8`. Labels above fields is missing that style. It changes the relationship with elements like children and `:before` that are given  `position: absolute` (which will cuddle up with the closest ancestor that has a non-`static` position set).

**Comment by knod** [comment]
One possible change that could be helpful while this transition is going on is to add a `.da-top-label` to some container, not just the `label` itself. That would allow for some conditional styling.

**Comment by jhpyle** [comment]
If you need `dafieldpart` to have `positition: relative` you can add a rule in your own custom CSS:
```
.dafieldpart {
    position: relative;
}
```
I am trying to keep the HTML as simple as possible and to adhere to Bootstrap 4 standards.  https://getbootstrap.com/docs/4.0/components/forms/
If there is something you need to do and it is impossible to do it with the existing DOM structure, let me know specifically what it is.

**Comment by knod** [comment]
The problem isn't that it can't be added, it's that this setting creates unintended side effects on styles for the page. Or at least, style and DOM access side effects were my concern when creating this issue.
