### ISSUE TITLE
Always getting 403 access denied response when using post request

### ISSUE THREAD

**Issue by chunhai** [jhpyle/docassemble#212]
Hi,

When I try to make a post request using the API provided by docassemble, it always gives a response code of 403 (access denied). Nevertheless, with the same api key, it can give me correct responses when making a get request. An example of code is like this:

`   r = requests.post(
        url="http://******.****.compute.amazonaws.com/api/session",
        data={'key': api_key, 'i': file_name, 'session': session_id, 'variables': {'exp': '11111'}},
        verify=False
    )`

Why the api key cannot authenticate when making post request? I also checked the role of the owner of this api_key, and its admin. Any idea how to fix this? Thank you!

Best,
Chunhai

**Comment by jhpyle** [comment]
Look in the Logs in the `docassemble.log` file for error messages that begin with `api_verify`.  That will provide more information about why the 403 error happened.

**Comment by chunhai** [comment]
Hey Jhpyle:

Thank you for the quick response!

I checked the log and it says "api_verify: no API key provided", but I did provide the API key as shown in example above. Am I using the wrong format to make a post request?

Best,
Chunhai

**Comment by jhpyle** [comment]
Do you normally access your site with `https://`?  Is your site redirecting when you call it using `http://`?  Why did you add `verify=False`?

**Comment by chunhai** [comment]
> Do you normally access your site with `https://`? Is your site redirecting when you call it using `http://`? Why did you add `verify=False`?

I think that's the reason. I am configuring it to http now and it works fine. Thank you for your help.
