### ISSUE TITLE
Problem with quotes in a dropdown selection.

### ISSUE THREAD

**Issue by JCCChris** [jhpyle/docassemble#214]
Using code like this to populate the options for a select: 
`for _row in _locations:
    an_option = _row["FIELD1"].replace("<br/>"," - ") +" - " + _row["FIELD2"].replace("<br/>"," , ")
    if conditional_here:
      _location_options.append( an_option )`

And using code like this to show it:

`  - "Which location?": myDADict[i].location
    code: |
      _location_options
    required: True`

Results in truncation of the form field value when there are double quotes in the values.

The data causing the problem has curly start and end quotes.  Like:

`... “A” ... “B” ...`

**Comment by jhpyle** [comment]
I think this was addressed in the above commit but reopen if not.
