### ISSUE TITLE
Python 3 support for testing

### ISSUE THREAD

**Issue by niharikasingh** [jhpyle/docassemble#220]
Behavior driven testing currently relies on Lettuce. However, Lettuce doesn't seem to work on Python 3, based on my difficulties using it and [this issue:](https://github.com/gabrielfalcao/lettuce/issues/458)

[Aloe](https://github.com/aloetesting/aloe) seems to be a good replacement for Python 3 users. I was able to get Aloe up and running with only the following minor changes. Would it be possible to make these changes and mention them in the documentation? 

## `docassemble.py`
1. `tests/features/steps/docassemble.py` renamed to `tests/features/__init.py__` 
1. `from lettuce import step, world` changed to `from aloe import step, world`
1. All the steps changed to use regexes instead of strings. So: `@step('I spend at least ([0-9]+) seconds? on each page')` changed to `@step(r'I spend at least ([0-9]+) seconds? on each page')`

## `terrain.py`
1. All lettuce imports replaced with `from aloe import *`
1. The `tear_down()` function didn't work out of the box. I made it work by removing functionality, but it might be possible to work while retaining all the original functionality, it would just require some investigation. My current working function looks like: 
```python
def tear_down():
    world.browser.quit()
```

## Documentation
1. The documentation will need to be updated to account for the above changes. 

Please let me know if you have any questions about the above. I'm happy to help implement the above changes if the maintainers agree they are warranted.

**Comment by jhpyle** [comment]
Thanks!  I made these changes in 0.5.38. Let me know if you find any problems with it.

**Comment by niharikasingh** [comment]
Just one comment - I had to move the location of `docassemble.py` to get this to work in my repo. It went from `tests/features/steps/docassemble.py` to `tests/features/__init.py__`. If you've tested that your way works too, then that's fine!

**Comment by jhpyle** [comment]
Did you try creating empty `__init__.py` files in `tests/features` and `tests/features/steps`?  That was what worked for me.

**Comment by jhpyle** [comment]
I am keeping this issue open because maybe it makes sense to transition to `pytest-bdd` instead of aloe?  I don't know; I haven't tried `pytest-bdd` yet but it seems to be recommended.

**Comment by niharikasingh** [comment]
> Did you try creating empty `__init__.py` files in `tests/features` and `tests/features/steps`? That was what worked for me.

I didn't try that! If it works, that's great. I'll try it next time I work on my docassemble project.

**Comment by jhpyle** [comment]
I migrated all testing to Aloe and it seems to work, so I am closing this issue.  Thanks!
