### ISSUE TITLE
LDAP Login Problems (Python 3 + Docker)

### ISSUE THREAD

**Issue by stphg** [jhpyle/docassemble#221]
First of all, many thanks to this great software. Love it!

We use it now for a few weeks for testing and are looking to make it to production. However, as we use it on our servers in a docker env, I want to use our internal LDAP for user authentication. I don' know if i get the wrong impression, but several Problems appeared:

1. python-ldap is missing in the Python 3.6 Package requirements. Not a big problem, as i can manually install it with the package management. Nevertheless, should be installed or mentioned in the docs.

2. python-ldap 3.1.0 and above removed _ldap.open()_, which is used in the code. Therefore, only 3.0.0 and below can be used. Also not a big problem, but also should be mentioned or fixed.

3. If I use python-ldap=3.0.0 with our LDAP-Server, it is possible to lookup the information on the LDAP Server and login. However, it is also possible to login without any user or password information. The authentication can be bypassed. Following config minimal config is used for LDAP:
`
ldap login:
  enable: True
  server: 192.168.x.xx 
`
I also use the standard authentication for the admin at the moment. I would really be nice to use ldap, as we don't want to push it to the cloud or open ports at the moment.

If you like, I can try to open an PR, but if you can fix it easily, this will be faster. 

Many thanks in advance.

**Comment by jhpyle** [comment]
Sorry about that, I disabled the ldap feature in the Python 3 version for some reason and I haven't tested it since I wrote the code.  I also forgot to make a note that I needed to fix the ldap feature, so it hasn't been working for a while.  If you can get it working I would definitely like to see a PR showing what you did.

**Comment by stphg** [comment]
Ah, ok. No problem.

I think it shouldn't be that hard, but I'm far away from a LDAP/AD expert. 
Nevertheless, I can try it. It should only be a matter of one or two tweaks in the try/expect block in the LoginForm.
