### ISSUE TITLE
When login page is cached, CSRF error occurs

### ISSUE THREAD

**Issue by JCCChris** [jhpyle/docassemble#241]
When using "continue where you left off" feature of Chrome, if the login page is cached and the browser pulls up the cached version, even after logging in with proper credentials, CSRF error occurs.

**Comment by jhpyle** [comment]
The page is delivered with headers telling the browser not to cache the page.  This is a Chrome problem as far as I am concerned.

**Comment by JCCChris** [comment]
Seems like my mistake when describing the issue.  The intent when using "continue where you left off" is not to reload the page.  It's to "continue where you left off" which is not intended to check for cacheing or even load the page from the server.  Regardless, it's your right to refuse to handle this situation.  Thank you for all your help.

**Comment by jhpyle** [comment]
Maybe Google wants an internet where every single web page is a JavaScript application that runs code on an interval and constantly eats up CPU on a device.  I just don't feel like enabling that.  I set the headers to say the page was volatile, so if Chrome decided to cache it, that's on Chrome.
