### ISSUE TITLE
Feature: Set github `user.email` manually

### ISSUE THREAD

**Issue by knod** [jhpyle/docassemble#242]
Allow a Playground user to input the email they want to be used for the `user.email` config option.

**Comment by knod** [comment]
This can allow things like using your private Github email as opposed to your private one. People will still be able to contact you, they just won't be able to see your personal email address.

**Comment by jhpyle** [comment]
Closing because not necessary.

**Comment by knod** [comment]
Thanks for the fix that made this unnecessary!
