### ISSUE TITLE
Exception thrown in case_id_in_caption()

### ISSUE THREAD

**Issue by tjdaley** [jhpyle/docassemble#249]
This issue relates to **docassemble.base.legal.py**.

When I invoke **Case.case_id_in_caption()** in a context in which the result from run_hook() is None, but where my instance of Case has the *case_id* attribute, an exception is thrown saying that case does not have an attribute case:

> Interview has an error. There was a reference to a variable 'case.case' that could not be looked up in the question file (for language 'en') or in any of the files incorporated by reference into the question file.

I have two attachments:

1. [test.yml.txt](https://github.com/jhpyle/docassemble/files/4022280/test.yml.txt) - Works
1. [fails.yml.txt](https://github.com/jhpyle/docassemble/files/4022281/fails.yml.txt) - Fails

Based on my use, which is nascent, I believe the method should be changed from:

```python
   def case_id_in_caption(self, **kwargs):
        """Returns the text for the case ID that will appear in the case
        caption.
        """
        result = run_hook('case', self, 'case_id_in_caption', self.court.jurisdiction, **kwargs)
        if result is None:
            if hasattr(self, 'case_id'):
                return word('Case No.') + " " + self.case.case_id
            else:
                return word('Case No.')
        return result
```
to

```python
   def case_id_in_caption(self, **kwargs):
        """Returns the text for the case ID that will appear in the case
        caption.
        """
        result = run_hook('case', self, 'case_id_in_caption', self.court.jurisdiction, **kwargs)
        if result is None:
            if hasattr(self, 'case_id'):
                return word('Case No.') + " " + self.case_id  # This is the change.
            else:
                return word('Case No.')
        return result
```

**Comment by jhpyle** [comment]
This was fixed in 0.5.72.  Thanks!
