### ISSUE TITLE
Security audit status

### ISSUE THREAD

**Issue by tantrev** [jhpyle/docassemble#25]
Since docassemble seems amenable for collecting personally identifiable information, I am just curious if it has had any formal security audits.

**Comment by jhpyle** [comment]
The [security section](https://docassemble.org/docs/security.html) of the documentation contains an informal self-audit, but no formal security audit has been done.  At some point I may apply for a [pro bono security audit from Websec](http://websec.ca/opensource-web-security-campaign).

**Comment by jhpyle** [comment]
I am closing this issue because it is really old. Some formal security audits have been done but none I know of have been finished.
