### ISSUE TITLE
Add CloudConvert API

### ISSUE THREAD

**Issue by alexjsteffen** [jhpyle/docassemble#253]
Hey there, 

I have to mention that I have been using Docassemble personally for some time now and it's a great platform. I'm a lawyer in Toronto and Montreal, Canada, and I work with a lot of technology start ups -- but one of my hobbies is also being an amateur sysadmin. I'm in the right occupation. 

Nevertheless, I was wondering  if you are planning to also support CloudConvert in addition to ConvertAPI on Docassemble. They just launched a new version of their website and their API is quite easy to integrate. [Link](https://cloudconvert.com/api/v2)

They also have a [Python](https://github.com/cloudconvert/cloudconvert-python) API wrapper as well. 

I may attempt to integrate it myself but if it's officially supported, that would be ideal. 

Cheers,

**Comment by jhpyle** [comment]
I hadn't heard of CloudConvert, but I looked it up and added support for it in the same way ConvertAPI is supported.  Try version 0.5.77 and let me know if it gives you any problems.  When using Office to convert to PDF, it doesn't seem to support the password-protection feature or the PDF/A feature, even though the API has fields for it.

**Comment by alexjsteffen** [comment]
Interesting. Thank you so much, Jonathan, I appreciate it. I will experiment with it and let you know if I have any issues. 

Keep up the good work!

**Comment by alexjsteffen** [comment]
> I hadn't heard of CloudConvert, but I looked it up and added support for it in the same way ConvertAPI is supported. Try version 0.5.77 and let me know if it gives you any problems. When using Office to convert to PDF, it doesn't seem to support the password-protection feature or the PDF/A feature, even though the API has fields for it.
> 
> See https://docassemble.org/docs/config.html#cloudconvert%20secret

Update: It works well. I use custom fonts embedded within my .docx templates and it did the job well.
