### ISSUE TITLE
On the Pull screens, tab skips branch

### ISSUE THREAD

**Issue by michaelhofrichter** [jhpyle/docassemble#255]
On the pull screens from github into the playground or in package management, if you hit tab to move to the next field after entering the github link, it jumps to the PyPi box and skips the branch dropdown branch.

I've noticed this because I was testing something beyond the master branch

**Comment by jhpyle** [comment]
I am going through old issues today. I think this issue was fixed, so I am closing it. Thanks for reporting it!
