### ISSUE TITLE
NoneType Error trying to create signatures in latest docker

### ISSUE THREAD

**Issue by aphelionz** [jhpyle/docassemble#256]
Hello! Love docassemble. Thank you so much for creating and maintaining it.

I'm setting up a very simple "docusign" type service for a client and I almost have the interview configured. However when I click "Continue" after scribbling a signature, I get the following error:

![image](https://user-images.githubusercontent.com/106148/73016537-072a2480-3dec-11ea-9551-5b1d63376110.png)

```
Traceback (most recent call last):
  File "/usr/share/docassemble/local3.6/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/share/docassemble/local3.6/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/share/docassemble/local3.6/lib/python3.6/site-packages/docassemble/webapp/server.py", line 5802, in index
    theImage = base64.b64decode(re.search(r'base64,(.*)', post_data['_the_image']).group(1) + '==')
AttributeError: 'NoneType' object has no attribute 'group'
```

Here is my very minimal single-question interview that reproduces it:

```yaml
question: |
  Sign your name
subquestion: |
  By signing your name, you agree to
  our terms and conditions.
signature: signature
mandatory: true
```

I'm thinking perhaps it's a simple config issue and not a bug?

**Comment by jhpyle** [comment]
I wonder whether there is a JavaScript error on the screen with the signature.  Are you adding any JavaScript through a configuration directive?  Do you have any browser extensions that might be altering the data the web browser is sending?

**Comment by aphelionz** [comment]
Aha! I had device recognition blocked. Sorry, and thanks again.
