### ISSUE TITLE
Document referrer sending or provide workaround

### ISSUE THREAD

**Issue by kud1ing** [jhpyle/docassemble#27]
I have sending of the referrer disabled for privacy reasons and i can imagine many people do so, too.

In this case answering a question on https://demo.docassemble.org/ returns a "Bad Request".

I think it would be an improvement to either:
* document if docassemble can not work without referrer sending
* maybe there is a workaround for this requirement?

**Comment by jhpyle** [comment]
When HTTPS is used, the [CSRF protection mechanism](http://flask-wtf.readthedocs.io/en/stable/csrf.html) checks the referer header to see if it matches the host and throws an error if the referer is not set.

This behavior is [configurable](http://flask-wtf.readthedocs.io/en/stable/config.html) using the `WTF_CSRF_SSL_STRICT` configuration setting.

I am adding a **docassemble** configuration directive called `require referer` that can be used to disable this security feature in case the system administrator wants to permit users to use referer blockers.

I will update this issue when the new version of **docassemble** is published.

**Comment by kud1ing** [comment]
I see, thank you.

**Comment by jhpyle** [comment]
The `require referer` setting is available in version 0.1.41.  See the [documentation](https://docassemble.org/docs/config.html#require referer).

On https://demo.docassemble.org, I have enabled the setting `require referer: False` so you can test it out, at least for the next few weeks.

Even without this setting, docassemble should be compatible with browser add-ons that hide the referer only across domains.  (E.g., [this add-on](https://addons.mozilla.org/en-US/firefox/addon/no-cross-domain-referer/).)
