### ISSUE TITLE
Private Access Tokens for Github are Deprecated

### ISSUE THREAD

**Issue by michaelhofrichterHVL** [jhpyle/docassemble#270]
Per [Github](https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/), personal access tokens are deprecated and will no longer work after November 2020. 

As I see it now, that's the [instructions in Docassemble](https://docassemble.org/docs/packages.html#github_install) for using private repositories.

I'm at least getting an email from Github the first time I do this on a server.

**Comment by jhpyle** [comment]
I don't think that page says that personal access tokens are deprecated.  It says that authentication through query parameters is deprecated, and putting a personal access token in a query parameter is one way in which authentication happens through query parameters.

The usage I describe involves putting a personal access token into the header of an HTTP request using Basic Authentication.  GitHub has added deprecation warnings in its documentation in a number of places, but the section on authenticating through basic authentication doesn't have a warning attached to it.

I tried to trigger that e-mail from GitHub by creating a new personal access token and accessing a private repository using it, but it didn't send me anything.  Could you copy and paste the e-mail?

**Comment by michaelhofrichterHVL** [comment]
Hi @michaelhofrichterHVL,

On March 24th, 2020 at 04:15 (UTC) your personal access token (Interviews Personal Access Token) using Python-httplib2/0.14.0 (gzip) was used as part of a query parameter to access an endpoint through the GitHub API:

https://api.github.com/repositories/241675372/branches

Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated. If this token is being used by an app you don't have control over, be aware that it may stop working as a result of this deprecation.

Depending on your API usage, we'll be sending you this email reminder on a monthly basis for each token and User-Agent used in API calls made on your behalf.
Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.

Visit https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param for more information about suggested workarounds and removal dates.

Thanks,
The GitHub Team

**Comment by nonprofittechy** [comment]
I received this same message a few weeks ago when I created a private repo
