### ISSUE TITLE
502 Bad Gateway nginx on docker image

### ISSUE THREAD

**Issue by lattice0** [jhpyle/docassemble#279]
a

**Comment by jhpyle** [comment]
There is probably a configuration error.  For troubleshooting options, see https://docassemble.org/docs/docker.html#troubleshooting

**Comment by lucaszanella** [comment]
But I simply started the docassemble, with no configuration

**Comment by jhpyle** [comment]
To try to reproduce the problem you saw, I started a fresh EC2 instance on AWS, opened port 8080 on the firewall, ran `docker run -p 8080:80 jhpyle/docassemble`, and after 1 minute 30 seconds, I visited http://<ip address>:8080 in my browser and the "It works!" interview came up.

According to the logs above, uwsgi exited unexpectedly with code 137.  I Googled exit code 137 and a lot of the results suggest it is associated with an "out of memory" KILL signal.  How much available RAM does your machine have?
