### ISSUE TITLE
How to set default value to date type input field

### ISSUE THREAD

**Issue by vrst37** [jhpyle/docassemble#281]
I need to set a default value to date type input field. How would we go about doing that?

I have tried things like this

```
---
question: |
  Information?
fields:
  - Date: phone_date
    datatype: date
    default: |
      as_datetime(today('dd/mm/yyyy'))
---
```

and a few other variations. I also scanned through the documentation and could not find a clear way.

Is there an easy solution to do this?

**Comment by nonprofittechy** [comment]
You need this date format: 
today().format('yyyy-MM-dd')

This does seem like a convenient thing to build-in somehow though.

**Comment by jhpyle** [comment]
Prior to 0.5.107, you had to format the default date in the format yyyy-MM-dd.  As of 0.5.107, you can just do `default: today()`.

**Comment by vrst37** [comment]
@jhpyle The solution you have proposed is not working

@nonprofittechy your solution has worked

**Comment by jhpyle** [comment]
Sorry, I forgot the Mako:
```
default: |
  ${ today() }
```

**Comment by vrst37** [comment]
I will test that and let you know if it is working.

But going by memory, that solution didn't work with mako either.

**Comment by jhpyle** [comment]
What version of docassemble are you using?

**Comment by vrst37** [comment]
I confirm that your solution is working. I was using an older version, way too old of a version.
