### ISSUE TITLE
Idea: Add Back Button on Error Page

### ISSUE THREAD

**Issue by josh-thurston** [jhpyle/docassemble#283]
Might be a good idea to add a back button when presented with an error similar to the image attached.  This will make the user experience more fluid
<img width="1109" alt="Screen Shot 2020-04-20 at 12 16 56 PM" src="https://user-images.githubusercontent.com/36908151/79780054-f745b200-8300-11ea-8676-a20d3d5f0d4f.png">

**Comment by jhpyle** [comment]
I added something similar.
