### ISSUE TITLE
Occasional Google Drive sync errors

### ISSUE THREAD

**Issue by nonprofittechy** [jhpyle/docassemble#29]
Occasionally with frequent saving / syncing, Docassemble overwrites the copy stored on Drive with a zero-byte file. Not sure if this is because of race condition with syncing?

**Comment by jhpyle** [comment]
Yikes.  If you notice this happen again, could you check the logs to see if it says anything out of the ordinary around the time this happens?  Also, just curious -- were you using S3 or Azure for persistent data storage when this happened?

In any case, I added some code in 0.1.48 that may prevent this from happening, but I need to test this more.
