### ISSUE TITLE
PDF not "decrypted" error

### ISSUE THREAD

**Issue by francisjervis** [jhpyle/docassemble#303]
Hi, I am trying to output a filled PDF [form](https://www.courts.ca.gov/documents/ud105.pdf) but DA throws an unexpected error: `PyPDF2.utils.PdfReadError: file has not been decrypted` at template compile.

This appears to be the same issue as [this](https://bugs.launchpad.net/pypdf/+bug/355479) and/or [this](https://stackoverflow.com/questions/26242952/pypdf-2-decrypt-not-working) issue with the PyPDF2 lib.

I was able to fix this for the linked PDF with the qpdf "decrypt" hack mentioned in one of the links, which strongly suggests this is in fact the issue. Suggested fix is to include the code at the SO link to pre-check PDFs for "encryption" on upload to the templates folder.

**Comment by jhpyle** [comment]
See https://docassemble.org/docs/documents.html#template%20password
The code behind this feature uses `qpdf` to do the "decryption."  Templates like these are a special case of encrypted templates; the password just happens to be `""`.
