### ISSUE TITLE
504 Gateway Time-out - Any expert ?

### ISSUE THREAD

**Issue by Soufiane-dev-it** [jhpyle/docassemble#304]
Hi, I created a simple interview that has 3 questions, and I used word document (786pages) "a Contract"
When I wait for the result in order to download the PDF or Doc, it shows **504 Gateway Time-out** after 60 seconds.

I increased COMPOSE_HTTP_TIMEOUT to 120sec in docker-composer.yml but without success

Is there any Docassemble setting I need to change?

I hope i will find an answer

**Comment by jhpyle** [comment]
A 786 page document will take a long time to assemble.  A web server needs to respond to the web browser within a few seconds.  So you will need to use a background task to assemble the document, which means making sure that you gather all the variables the assembly process will need, then launching the background process, then telling the user to wait.  (Or you could ask the user additional questions while the document is assembling in the background.)

See the final example in this section: https://docassemble.org/docs/background.html#ui_notification

**Comment by Soufiane-dev-it** [comment]
This will be the only solution I suppose.
Many thanks Jonathan, I will try it and update you

**Comment by Soufiane-dev-it** [comment]
Thanks for the solution, it's working perfect, it takes less than 5 mins for the doc to be ready I wished it will be less but it's good anyway.
