### ISSUE TITLE
websocket in docker not allowing live chat

### ISSUE THREAD

**Issue by japrogramer** [jhpyle/docassemble#311]
Created docker env from one line deployment in docs 
`docker run -d -p 80:80 -p 443:443 --stop-timeout 600 jhpyle/docassemble`

config
```
cross site domains:
  - http://ip.add.res.a
expose websockets: true
websockets ip: 127.0.0.1
websockets port: 5000
```
websocket.log
```
d6030b72175948c3b26657ba6983fe79: Sending packet OPEN data {'sid': 'd6030b72175948c3b26657ba6983fe79', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
d6030b72175948c3b26657ba6983fe79: Sending packet MESSAGE data 0
http://ip.add.res.a is not an accepted origin.
http://ip.add.res.a is not an accepted origin.
```

here i obfuscate the ip address but it is correctly typed in the config.

in aws I espose port 80 443 and 5000

**Comment by jhpyle** [comment]
Try upgrading to 1.1.83 and see if gives a different result.

**Comment by japrogramer** [comment]
That helped, I can now chat in some browsers.

However when i try to chat in a 
`firejail --private --dns=8.8.8.8 --dns=8.8.4.4 firefox` 
I can't send messages, is this indicating that the browser 
has to have some settings a certain way?

**Comment by jhpyle** [comment]
I don't have a problem using the websocket chat feature in Firefox running with firejail, so I don't know what that is about.

A lot depends on the specific configuration.  Errors in the console can provide clues.  Especially if you are doing anything cross-site, the browser might allow some traffic but not allow other traffic, if the cookies aren't just right.  Different browsers have different policies about what communications they block.  iOS Safari blocks cross-site cookies by default, unless the user changes their settings, so if you are embedding docassemble you should use a reverse proxy to host your docassemble server.  Passing websockets through a reverse proxy is complex, unfortunately.

**Comment by japrogramer** [comment]
I was able to get websockets to work in the firejail after closing and starting a new session.
It was probably an issue with the cache since I had the same session since updating docassemble.
