### ISSUE TITLE
Docker persistent Volume?

### ISSUE THREAD

**Issue by japrogramer** [jhpyle/docassemble#312]
Hello, I just had to quickly restart the docker container and because there is no persistent volume
all work I had done was lost including configuration.

Is there an easy way to make the docker image have persistent volume?

or would I need to create my own custom compose.yml  image for this?

**Comment by jhpyle** [comment]
Feel free to join the Docassemble Slack.  https://docassemble.org/docs/support.html

Persistent volume configuration is not part of a Docker image, but is something you set up during the `docker run` process.

The instructions on using persistent volumes are here: https://docassemble.org/docs/docker.html#persistent

**Comment by japrogramer** [comment]
Thank you for the link to the docker volume

however the slack channel leads to this
![image](https://user-images.githubusercontent.com/1387859/95413070-1c020600-08f0-11eb-8ff8-a14b2176702d.png)

And I am having a problem setting up ssl with the --env-file=env.file method .. the site becomes unreachable
and wget stalls with ":443..." and is correctly redirect with a 301 if http: is used.

**Comment by jhpyle** [comment]
I guess Slack got rid of their never-expire invite links.  Anyway the new link is here: https://join.slack.com/t/docassemble/shared_invite/zt-i1z6eg4j-_HFpFnuui_4EtHvKOmSb3A

If you don't set up HTTPS properly, it may crash on startup.  You can go into the container and check the logs to see what went wrong.  I recommend using Let's Encrypt, which means you need a custom domain name that is pointing to the machine and the machine needs ports 80 and 443 open to the outside world.

**Comment by japrogramer** [comment]
Thank you for the link but also that link led me to an error 
![image](https://user-images.githubusercontent.com/1387859/95414872-7e5d0580-08f4-11eb-8c0c-59839d8ae8bd.png)

which log file do i need to find for the lets encrypt or relevant logs? 

I enter the container like this, `docker exec -ti $(docker ps -f name="a" -q) bash`
so I would like to know the full path if possible otherwise a filename would also be fine
