### ISSUE TITLE
Feature request: just the facts, ma'am

### ISSUE THREAD

**Issue by superian** [jhpyle/docassemble#314]
There is a shortage of open-source, self-hosting web polling software.

LimeSurvey is extremely powerful, but I think even its fans would say that calling it "easy" is stretching things somewhat.

NextCloud Forms is more usable by mortals but wants you to buy into the whole NextCloud environment.

Drupal has a WebForms module, but it's Drupal (sorry to people who like it) and it doesn't have the brilliance of having YAML and Markdown to generate the forms.

Is it possible to have a version of docassmble that doesn't require the ability to output anything other than plain text, and so doesn't need to drag in LibreOffice, TeX etc?

**Comment by jhpyle** [comment]
Someone could make a Docker image that doesn't include those things.  It could pull in the latest versions of the docassemble Python packages from PyPI.  But I don't have the time or interest to maintain parallel versions.

**Comment by superian** [comment]
Yes, I totally understand that!
