### ISSUE TITLE
Vocabulary terms: Multiple terms with the same definition

### ISSUE THREAD

**Issue by FrankBold** [jhpyle/docassemble#315]
For vocabulary usage in other languages (czech in my case), would be usefull to be able to assing one term definition to multiple versions of the same term, at once. Reason is that single word can be slightly different for various context. Eg. "soud" (=court), "soudu", "soudem", "soudům". 

Something like:
```
terms:
  term1, term2, term3: |
    Definition of the terms
```

Also, could be nice to define terms using Python dictionary. It would make it easier externally  Like:
```
terms:
  - pythonDict
```

**Comment by jhpyle** [comment]
I added some features for this in 1.1.92.
https://docassemble.org/docs/functions.html#update_terms
https://docassemble.org/docs/initial.html#terms

**Comment by FrankBold** [comment]
That's perfect. Thank you!
