### ISSUE TITLE
Issue Connecting to Github

### ISSUE THREAD

**Issue by michaelhofrichter** [jhpyle/docassemble#316]
The error screen was longer than I can post in Slack, so I'm reporting it this way. 
I was able to link the site to the Github server after confirming my credentials (I think -- I started this last night and tried again today to see if the answer was the same). 
I go to the profile, then Github integration. Then I get the page to confirm the github Integration. I click Continue, and get a page that has the title "Error" (URL = https://interviews.bethyeshurun.org/github_configure). The body of the page is

b'{"url":"https://api.github.com/repos/jhpyle/docassemble/pulls/302","id":446340355,"node_id":"MDExOlB1bGxSZXF1ZXN0NDQ2MzQwMzU1","html_url":"https://github.com/jhpyle/docassemble/pull/302","diff_url":"https://github.com/jhpyle/docassemble/pull/302.diff","patch_url":"https://github.com/jhpyle/docassemble/pull/302.patch","issue_url":"https://api.github.com/repos/jhpyle/docassemble/issues/302","number":302,"state":"closed","locked":false,"title":"Clarify method to preserve user line breaks","user":{"login":"nonprofittechy","id":7645641,"node_id":"MDQ6VXNlcjc2NDU2NDE=","avatar_url":"https://avatars3.githubusercontent.com/u/7645641?v=4","gravatar_id":"","url":"https://api.github.com/users/nonprofittechy","html_url":"https://github.com/nonprofittechy","followers_url":"https://api.github.com/users/nonprofittechy/followers","following_url":"https://api.github.com/users/nonprofittechy/following{/other_user}","gists_url":"https://api.github.com/users/nonprofittechy/gists{/gist_id}","starred_url":"https://api.github.com/users/nonprofittechy/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/nonprofittechy/subscriptions","organizations_url":"https://api.github.com/users/nonprofittechy/orgs","repos_url":"https://api.github.com/users/nonprofittechy/repos","events_url":"https://api.github.com/users/nonprofittechy/events{/privacy}","received_events_url":"https://api.github.com/users/nonprofittechy/received_events","type":"User","site_admin":false},"body":"Rewrite of the section about line breaks in Jinja2 to highlight the new default behavior and clearly explain when and how line breaks in user input will be turned into paragraphs and other consequences of those options.","created_at":"2020-07-08T16:02:50Z","updated_at":"2020-10-15T23:50:48Z","closed_at":"2020-10-15T23:50:48Z","merged_at":"2020-10-15T23:50:48Z","merge_commit_sha":"a46d1abc08c9876eed5eaab18f1a1511ce3d8747","assignee":null,"assignees":[],"requested_reviewers":[],"requested_teams":[],"labels":[],"milestone":null,"draft":false,"commits_url":"https://api.github.com/repos/jhpyle/docassemble/pulls/302/commits","review_comments_url":"https://api.github.com/repos/jhpyle/docassemble/pulls/302/comments","review_comment_url":"https://api.github.com/repos/jhpyle/docassemble/pulls/comments{/number}","comments_url":"https://api.github.com/repos/jhpyle/docassemble/issues/302/comments","statuses_url":"https://api.github.com/repos/jhpyle/docassemble/statuses/8999a9f3e096f21346903841ca7cda99bc48f9de","head":{"label":"nonprofittechy:patch-19","ref":"patch-19","sha":"8999a9f3e096f21346903841ca7cda99bc48f9de","user":{"login":"nonprofittechy","id":7645641,"node_id":"MDQ6VXNlcjc2NDU2NDE=","avatar_url":"https://avatars3.githubusercontent.com/u/7645641?v=4","gravatar_id":"","url":"https://api.github.com/users/nonprofittechy","html_url":"https://github.com/nonprofittechy","followers_url":"https://api.github.com/users/nonprofittechy/followers","following_url":"https://api.github.com/users/nonprofittechy/following{/other_user}","gists_url":"https://api.github.com/users/nonprofittechy/gists{/gist_id}","starred_url":"https://api.github.com/users/nonprofittechy/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/nonprofittechy/subscriptions","organizations_url":"https://api.github.com/users/nonprofittechy/orgs","repos_url":"https://api.github.com/users/nonprofittechy/repos","events_url":"https://api.github.com/users/nonprofittechy/events{/privacy}","received_events_url":"https://api.github.com/users/nonprofittechy/received_events","type":"User","site_admin":false},"repo":{"id":104117832,"node_id":"MDEwOlJlcG9zaXRvcnkxMDQxMTc4MzI=","name":"docassemble","full_name":"nonprofittechy/docassemble","private":false,"owner":{"login":"nonprofittechy","id":7645641,"node_id":"MDQ6VXNlcjc2NDU2NDE=","avatar_url":"https://avatars3.githubusercontent.com/u/7645641?v=4","gravatar_id":"","url":"https://api.github.com/users/nonprofittechy","html_url":"https://github.com/nonprofittechy","followers_url":"https://api.github.com/users/nonprofittechy/followers","following_url":"https://api.github.com/users/nonprofittechy/following{/other_user}","gists_url":"https://api.github.com/users/nonprofittechy/gists{/gist_id}","starred_url":"https://api.github.com/users/nonprofittechy/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/nonprofittechy/subscriptions","organizations_url":"https://api.github.com/users/nonprofittechy/orgs","repos_url":"https://api.github.com/users/nonprofittechy/repos","events_url":"https://api.github.com/users/nonprofittechy/events{/privacy}","received_events_url":"https://api.github.com/users/nonprofittechy/received_events","type":"User","site_admin":false},"html_url":"https://github.com/nonprofittechy/docassemble","description":"A free, open-source expert system for guided interviews and document assembly, based on Python, YAML, and Markdown.","fork":true,"url":"https://api.github.com/repos/nonprofittechy/docassemble","forks_url":"https://api.github.com/repos/nonprofittechy/docassemble/forks","keys_url":"https://api.github.com/repos/nonprofittechy/docassemble/keys{/key_id}","collaborators_url":"https://api.github.com/repos/nonprofittechy/docassemble/collaborators{/collaborator}","teams_url":"https://api.github.com/repos/nonprofittechy/docassemble/teams","hooks_url":"https://api.github.com/repos/nonprofittechy/docassemble/hooks","issue_events_url":"https://api.github.com/repos/nonprofittechy/docassemble/issues/events{/number}","events_url":"https://api.github.com/repos/nonprofittechy/docassemble/events","assignees_url":"https://api.github.com/repos/nonprofittechy/docassemble/assignees{/user}","branches_url":"https://api.github.com/repos/nonprofittechy/docassemble/branches{/branch}","tags_url":"https://api.github.com/repos/nonprofittechy/docassemble/tags","blobs_url":"https://api.github.com/repos/nonprofittechy/docassemble/git/blobs{/sha}","git_tags_url":"https://api.github.com/repos/nonprofittechy/docassemble/git/tags{/sha}","git_refs_url":"https://api.github.com/repos/nonprofittechy/docassemble/git/refs{/sha}","trees_url":"https://api.github.com/repos/nonprofittechy/docassemble/git/trees{/sha}","statuses_url":"https://api.github.com/repos/nonprofittechy/docassemble/statuses/{sha}","languages_url":"https://api.github.com/repos/nonprofittechy/docassemble/languages","stargazers_url":"https://api.github.com/repos/nonprofittechy/docassemble/stargazers","contributors_url":"https://api.github.com/repos/nonprofittechy/docassemble/contributors","subscribers_url":"https://api.github.com/repos/nonprofittechy/docassemble/subscribers","subscription_url":"https://api.github.com/repos/nonprofittechy/docassemble/subscription","commits_url":"https://api.github.com/repos/nonprofittechy/docassemble/commits{/sha}","git_commits_url":"https://api.github.com/repos/nonprofittechy/docassemble/git/commits{/sha}","comments_url":"https://api.github.com/repos/nonprofittechy/docassemble/comments{/number}","issue_comment_url":"https://api.github.com/repos/nonprofittechy/docassemble/issues/comments{/number}","contents_url":"https://api.github.com/repos/nonprofittechy/docassemble/contents/{+path}","compare_url":"https://api.github.com/repos/nonprofittechy/docassemble/compare/{base}...{head}","merges_url":"https://api.github.com/repos/nonprofittechy/docassemble/merges","archive_url":"https://api.github.com/repos/nonprofittechy/docassemble/{archive_format}{/ref}","downloads_url":"https://api.github.com/repos/nonprofittechy/docassemble/downloads","issues_url":"https://api.github.com/repos/nonprofittechy/docassemble/issues{/number}","pulls_url":"https://api.github.com/repos/nonprofittechy/docassemble/pulls{/number}","milestones_url":"https://api.github.com/repos/nonprofittechy/docassemble/milestones{/number}","notifications_url":"https://api.github.com/repos/nonprofittechy/docassemble/notifications{?since,all,participating}","labels_url":"https://api.github.com/repos/nonprofittechy/docassemble/labels{/name}","releases_url":"https://api.github.com/repos/nonprofittechy/docassemble/releases{/id}","deployments_url":"https://api.github.com/repos/nonprofittechy/docassemble/deployments","created_at":"2017-09-19T19:17:40Z","updated_at":"2020-03-01T21:02:34Z","pushed_at":"2020-07-08T16:19:53Z","git_url":"git://github.com/nonprofittechy/docassemble.git","ssh_url":"git@github.com:nonprofittechy/docassemble.git","clone_url":"https://github.com/nonprofittechy/docassemble.git","svn_url":"https://github.com/nonprofittechy/docassemble","homepage":"https://docassemble.org","size":202521,"stargazers_count":1,"watchers_count":1,"language":"Python","has_issues":false,"has_projects":true,"has_downloads":true,"has_wiki":true,"has_pages":true,"forks_count":0,"mirror_url":null,"archived":false,"disabled":false,"open_issues_count":0,"license":{"key":"mit","name":"MIT License","spdx_id":"MIT","url":"https://api.github.com/licenses/mit","node_id":"MDc6TGljZW5zZTEz"},"forks":0,"open_issues":0,"watchers":1,"default_branch":"master"}},"base":{"label":"jhpyle:asdf","ref":"asdf","sha":"19164ff8d25f2da498754020d57643ce185f9191","user":{"login":"jhpyle","id":11341940,"node_id":"MDQ6VXNlcjExMzQxOTQw","avatar_url":"https://avatars3.githubusercontent.com/u/11341940?v=4","gravatar_id":"","url":"https://api.github.com/users/jhpyle","html_url":"https://github.com/jhpyle","followers_url":"https://api.github.com/users/jhpyle/followers","following_url":"https://api.github.com/users/jhpyle/following{/other_user}","gists_url":"https://api.github.com/users/jhpyle/gists{/gist_id}","starred_url":"https://api.github.com/users/jhpyle/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jhpyle/subscriptions","organizations_url":"https://api.github.com/users/jhpyle/orgs","repos_url":"https://api.github.com/users/jhpyle/repos","events_url":"https://api.github.com/users/jhpyle/events{/privacy}","received_events_url":"https://api.github.com/users/jhpyle/received_events","type":"User","site_admin":false},"repo":{"id":34148903,"node_id":"MDEwOlJlcG9zaXRvcnkzNDE0ODkwMw==","name":"docassemble","full_name":"jhpyle/docassemble","private":false,"owner":{"login":"jhpyle","id":11341940,"node_id":"MDQ6VXNlcjExMzQxOTQw","avatar_url":"https://avatars3.githubusercontent.com/u/11341940?v=4","gravatar_id":"","url":"https://api.github.com/users/jhpyle","html_url":"https://github.com/jhpyle","followers_url":"https://api.github.com/users/jhpyle/followers","following_url":"https://api.github.com/users/jhpyle/following{/other_user}","gists_url":"https://api.github.com/users/jhpyle/gists{/gist_id}","starred_url":"https://api.github.com/users/jhpyle/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jhpyle/subscriptions","organizations_url":"https://api.github.com/users/jhpyle/orgs","repos_url":"https://api.github.com/users/jhpyle/repos","events_url":"https://api.github.com/users/jhpyle/events{/privacy}","received_events_url":"https://api.github.com/users/jhpyle/received_events","type":"User","site_admin":false},"html_url":"https://github.com/jhpyle/docassemble","description":"A free, open-source expert system for guided interviews and document assembly, based on Python, YAML, and Markdown.","fork":false,"url":"https://api.github.com/repos/jhpyle/docassemble","forks_url":"https://api.github.com/repos/jhpyle/docassemble/forks","keys_url":"https://api.github.com/repos/jhpyle/docassemble/keys{/key_id}","collaborators_url":"https://api.github.com/repos/jhpyle/docassemble/collaborators{/collaborator}","teams_url":"https://api.github.com/repos/jhpyle/docassemble/teams","hooks_url":"https://api.github.com/repos/jhpyle/docassemble/hooks","issue_events_url":"https://api.github.com/repos/jhpyle/docassemble/issues/events{/number}","events_url":"https://api.github.com/repos/jhpyle/docassemble/events","assignees_url":"https://api.github.com/repos/jhpyle/docassemble/assignees{/user}","branches_url":"https://api.github.com/repos/jhpyle/docassemble/branches{/branch}","tags_url":"https://api.github.com/repos/jhpyle/docassemble/tags","blobs_url":"https://api.github.com/repos/jhpyle/docassemble/git/blobs{/sha}","git_tags_url":"https://api.github.com/repos/jhpyle/docassemble/git/tags{/sha}","git_refs_url":"https://api.github.com/repos/jhpyle/docassemble/git/refs{/sha}","trees_url":"https://api.github.com/repos/jhpyle/docassemble/git/trees{/sha}","statuses_url":"https://api.github.com/repos/jhpyle/docassemble/statuses/{sha}","languages_url":"https://api.github.com/repos/jhpyle/docassemble/languages","stargazers_url":"https://api.github.com/repos/jhpyle/docassemble/stargazers","contributors_url":"https://api.github.com/repos/jhpyle/docassemble/contributors","subscribers_url":"https://api.github.com/repos/jhpyle/docassemble/subscribers","subscription_url":"https://api.github.com/repos/jhpyle/docassemble/subscription","commits_url":"https://api.github.com/repos/jhpyle/docassemble/commits{/sha}","git_commits_url":"https://api.github.com/repos/jhpyle/docassemble/git/commits{/sha}","comments_url":"https://api.github.com/repos/jhpyle/docassemble/comments{/number}","issue_comment_url":"https://api.github.com/repos/jhpyle/docassemble/issues/comments{/number}","contents_url":"https://api.github.com/repos/jhpyle/docassemble/contents/{+path}","compare_url":"https://api.github.com/repos/jhpyle/docassemble/compare/{base}...{head}","merges_url":"https://api.github.com/repos/jhpyle/docassemble/merges","archive_url":"https://api.github.com/repos/jhpyle/docassemble/{archive_format}{/ref}","downloads_url":"https://api.github.com/repos/jhpyle/docassemble/downloads","issues_url":"https://api.github.com/repos/jhpyle/docassemble/issues{/number}","pulls_url":"https://api.github.com/repos/jhpyle/docassemble/pulls{/number}","milestones_url":"https://api.github.com/repos/jhpyle/docassemble/milestones{/number}","notifications_url":"https://api.github.com/repos/jhpyle/docassemble/notifications{?since,all,participating}","labels_url":"https://api.github.com/repos/jhpyle/docassemble/labels{/name}","releases_url":"https://api.github.com/repos/jhpyle/docassemble/releases{/id}","deployments_url":"https://api.github.com/repos/jhpyle/docassemble/deployments","created_at":"2015-04-18T02:09:32Z","updated_at":"2020-10-20T04:07:09Z","pushed_at":"2020-10-20T04:07:06Z","git_url":"git://github.com/jhpyle/docassemble.git","ssh_url":"git@github.com:jhpyle/docassemble.git","clone_url":"https://github.com/jhpyle/docassemble.git","svn_url":"https://github.com/jhpyle/docassemble","homepage":"https://docassemble.org","size":209118,"stargazers_count":370,"watchers_count":370,"language":"Python","has_issues":true,"has_projects":true,"has_downloads":true,"has_wiki":true,"has_pages":true,"forks_count":148,"mirror_url":null,"archived":false,"disabled":false,"open_issues_count":33,"license":{"key":"mit","name":"MIT License","spdx_id":"MIT","url":"https://api.github.com/licenses/mit","node_id":"MDc6TGljZW5zZTEz"},"forks":148,"open_issues":33,"watchers":370,"default_branch":"master"}},"_links":{"self":{"href":"https://api.github.com/repos/jhpyle/docassemble/pulls/302"},"html":{"href":"https://github.com/jhpyle/docassemble/pull/302"},"issue":{"href":"https://api.github.com/repos/jhpyle/docassemble/issues/302"},"comments":{"href":"https://api.github.com/repos/jhpyle/docassemble/issues/302/comments"},"review_comments":{"href":"https://api.github.com/repos/jhpyle/docassemble/pulls/302/comments"},"review_comment":{"href":"https://api.github.com/repos/jhpyle/docassemble/pulls/comments{/number}"},"commits":{"href":"https://api.github.com/repos/jhpyle/docassemble/pulls/302/commits"},"statuses":{"href":"https://api.github.com/repos/jhpyle/docassemble/statuses/8999a9f3e096f21346903841ca7cda99bc48f9de"}},"author_association":"CONTRIBUTOR","active_lock_reason":null,"merged":true,"mergeable":false,"rebaseable":false,"mergeable_state":"dirty","merged_by":{"login":"jhpyle","id":11341940,"node_id":"MDQ6VXNlcjExMzQxOTQw","avatar_url":"https://avatars3.githubusercontent.com/u/11341940?v=4","gravatar_id":"","url":"https://api.github.com/users/jhpyle","html_url":"https://github.com/jhpyle","followers_url":"https://api.github.com/users/jhpyle/followers","following_url":"https://api.github.com/users/jhpyle/following{/other_user}","gists_url":"https://api.github.com/users/jhpyle/gists{/gist_id}","starred_url":"https://api.github.com/users/jhpyle/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jhpyle/subscriptions","organizations_url":"https://api.github.com/users/jhpyle/orgs","repos_url":"https://api.github.com/users/jhpyle/repos","events_url":"https://api.github.com/users/jhpyle/events{/privacy}","received_events_url":"https://api.github.com/users/jhpyle/received_events","type":"User","site_admin":false},"comments":0,"review_comments":0,"maintainer_can_modify":false,"commits":2,"additions":63,"deletions":45,"changed_files":1}'

**Comment by jhpyle** [comment]
Fixed in 1.1.91.  Sorry about that!
