### ISSUE TITLE
Setting cache=0 in API calls to start a new interview doesn't read templates from disk

### ISSUE THREAD

**Issue by jtyler22** [jhpyle/docassemble#321]
In the `Editing locally and running interviews in the Playground` section of the docs, it says you can set `cache=0` to force re-reading the interview from disk.

When calling the normal browser URL, i.e. `/interview?i=docassemble.playground1:interview.yml&cache=0&reset=1`, setting `cache=0` does work, i.e. it re-reads the interview (and templates). But it does not work when calling by API, i.e. `/api/session/new?key=api_key&i=docassemble.playground1:interview.yml&cache=0&reset=1`.

In the `How sessions work` section of the docs, it says, "If you are sending HTTP requests to **docassemble** using your own software, you only need to worry about URL parameters when sending a GET request to start an interview session or switch to a different session." I'm not sure whether it's referring to a normal browser URL or an API URL, but in any case, adding `cache=0` to an API call to `/api/session/new` does not force re-reading the interview from disk.

My use case is I am editing interviews and templates from disk and testing with a Python script that uses the API, but when I make a change to a template to disk and re-run the script, the previously cached template is the one used. As a temporary workaround, I modified the Python script to call the normal browser URL first (thus forcing re-reading), and then abandoning that session and continuing with the API in a new session.

(I would have submitted a pull request, but I couldn't find the section in the code that parses the `cache=0` argument.)

**Comment by jhpyle** [comment]
If `/api/session/new` had a `cache` parameter, that would have been documented in the API section.

The API endpoint for uploading files into the Playground clears the cache.

Anyway, I added an [API endpoint](https://docassemble.org/docs/api.html#clear_cache) for clearing the cache.

**Comment by jtyler22** [comment]
Wow, that was fast! Thanks so much, this will be very helpful.
