### ISSUE TITLE
Docassemble is initialized unexpectedly

### ISSUE THREAD

**Issue by primedev22** [jhpyle/docassemble#322]
Now I am using Azure App Service to deploy my docassemble using docker. It worked fine for several days, but finally, it was initialized and all the data is lost. I could log in using the initial admin user and password. I guess this issue occurs when App Service reboots. I am not sure about the reason and how to recover the interviews.
FYI, I deployed docassemble following this guide: https://gist.github.com/jasonbarbee/a52ffb2df46da78d2383e2980cdb7880
Is there any way to fix this issue? Thank you in advance!

**Comment by jhpyle** [comment]
I don't know how Azure App Service works or if it is compatible with docassemble.  (I would guess it would only be compatible if you ran it in a manner where the container was fully disposable, meaning that it was deployed with Azure Blob Storage, external Redis, and external SQL.)

If Azure App Service created a virtual machine behind the scenes, you could see if you could ssh to the virtual machine.  Maybe there would still be some old docker containers on that machine, which you could see by running `docker ps -a`.  Your data would be in one of those old containers.

I recommend deploying docassemble by running a virtual machine on a cloud provider, connecting to the virtual machine via the command line, and running `docker` commands.  (Or if you need a multi-server configuration, using Kubernetes and Helm.)  I have several docassemble containers running on Azure, using virtual machines running Ubuntu.

**Comment by primedev22** [comment]
Really appreciate your reply, @jhpyle . 
It seems there is no way to recover the interviews while I was using Ap Service, so my next plan is to deploy docassembe in a safer way. (This means that data should remain even though the machine has to be rebooted.)

**Comment by jhpyle** [comment]
Rebooting the VM is not a problem as long as the VM shuts down the Docker container in such a way that it allows for sufficient time for the container to safely shut down.  When starting from the command line, `--stop-timeout 600` tells Docker that the container should be given up to ten minutes to shut down safely (not that it really needs that much time).  You can also add `--restart unless-stopped` to `docker run` and then the container will automatically start when the VM reboots.
