### ISSUE TITLE
set_language overridden by attachment / language

### ISSUE THREAD

**Issue by cschwarz007** [jhpyle/docassemble#323]
Hi Jonathan,

Amazing what you developed here! Many thanks!

One thing I noticed in v1.1.100 is that a language setting via set_language() is overridden by a language setting in attachments. In essence, the following code leads to the language being set to english for all questions and not only for the attachment. 

```
---
initial: True
   set_language('de')
---
question: |
   A question here
attachments:
  - name: NDA
    language: en
    ...
---
```

Is this intended behavior? I interpreted the documentation that the language modifier for the attachment only modifies the attachment language (and not all questions)...?

Regards,
Christian

**Comment by jhpyle** [comment]
Sorry about that!  I think I fixed the issue in 1.1.102 but reopen this issue if you still have problems.  Thanks very much!
