### ISSUE TITLE
Filename attribute for attachments / order of processing

### ISSUE THREAD

**Issue by cschwarz007** [jhpyle/docassemble#324]
Dear Jonathan,

My scenario is that I generade documents in docx and pdf format from a docx template. In the footer, the docx template has a Word field for the filename (as for the user it is important to identify the document by the name). I set the filename via `filename `attribute. However, the order of internal processing seems to be that the PDF file is generated prior to the docx filename being set. The PDF file always shows "file.docx" in the footer (which corresponds with the return value of `doc_variable.docx.path()`) while the UI offers the files with the correct name (albeit from a different path than the internal document path variable). It would be desirable to have the filename set prior to PDF generation. Any chance this can be changed or ideas for a workaround that might result in the desired result? Note that the resulting word documents needs to remain dynamic when it comes to the filename as the user may want to download, modify and rename the document...

Many thanks for your support!
Christian

**Comment by jhpyle** [comment]
I'm not sure how you are getting `doc_variable.docx.path()` into the text of a DOCX file.  There's a chicken-and-egg problem; the `DAFileCollection` object doesn't exist until the template is assembled, but the template cannot be assembled until the `DAFileCollection` exists.  I get an infinite loop when I try to do that.  How exactly are you including `doc_variable.docx.path()`?  Maybe you could share some YAML and a copy-and-paste from the DOCX file.

I wouldn't use the `path()` because that is an internal file system path that is always going to end in `file.docx`.  The actual filename that the user sees would be `doc_variable.info['filename'] + '.docx'` but as far as I know that is only accessible after the file is assembled.

**Comment by cschwarz007** [comment]
My apologies - apparently the description was not clear. I am using `doc_variable.docx.path()` only for debug purposes... 

This is my YAML code to generate the files (DOCX and PDF):
```
---
mandatory: True
decoration: file-contract
question: |
  Here is your NDA.
subquestion:
  Does this NDA fulfill all your requirements?
field: requirements_fulfilled
buttons:
  - "Yes": True
  - "No": False
attachments:
  - name: NDA
    filename: ${ 'NDA_'+ BDF_company[0].name.text + '_' + Other_party[0].name.text }
    variable name: NDA
    docx template file: 
      code: |
        template_file
    valid formats:
      - pdf
      - docx
allow emailing: False      
---
```
However, despite the fact that I set a filename, the PDF file shows in the footer "file.docx". The footer is based on a word formula field which is pulling the document name. Hence, I was assuming that the PDF file is generated based on a docx file which is created prior to applying the filename. If this order can be reversed, i. e. first rename the created docx file prior to PDF generation, the issue would be solved...

![file](https://user-images.githubusercontent.com/20018714/99717657-f731ae80-2aa9-11eb-888c-bfb03aa9c3c7.png)

**Comment by nonprofittechy** [comment]
Since you know the filename when it's generated and that never needs to be updated for the PDF, can you just use some conditional logic?

```
objects:
  - my_attachments: DADict
---
attachment:
  variable name: my_attachments[i]
  docx template file: my_file.docx
---
question: |
  download pdf: ${ my_attachments['pdf_version'].pdf}
  download docx: ${ my_attachments['docx_version'].docx }
```

and in the docx:
```
{%p if i = 'pdf_version' %}
{{ my_attachments['docx_version'}.filename }}  // if this causes a loop, you could just directly store the file name as a variable
{%p else %}
[YOUR FIELD CODE HERE]
{%p endif %}
```

**Comment by jhpyle** [comment]
Ok, I see - you meant the special Word feature for inserting the local file name, not a Jinja2 field that inserted a file name.  The file path on the server is not going to be helpful, and it isn't configurable.  So I would not use the Word feature.  I would suggest substituting a Jinja2 variable with `{{` and `}}` that plugs in the same thing that you are using for the `filename` of the `attachment`.

**Comment by cschwarz007** [comment]
Quinten, many thanks for your suggestions. That works like a charm (and I could not think of it).

Jonathan, thank you for your suggestion as well. But using Jinja2 in the Word would lead to the loss of the dynamic behavior of the field. And the usage scenario is that the user often downloads the DOCX file and renames it - hence expects the footer to show the (then) changed filename.

**Comment by jhpyle** [comment]
Try 1.1.104.
