### ISSUE TITLE
countries_list() in local language

### ISSUE THREAD

**Issue by cschwarz007** [jhpyle/docassemble#325]
Hi,
I am using countries_list for contract parties and to generate a contract based on this. Contract languages include other languages besides English. Hence it would be helpful to also get country names in other languages than English. Any chance this can be achieved with the current functionality?

**Comment by jhpyle** [comment]
In 1.1.103 I changed it so that country names automatically pass through the `word()` translation system.  So you can go to Utilities -> "Translate system phrases into another language" and create a translation file that translates the country names.  Then you can put that file in the sources folder of a package and reference that file in your server Configuration under the `words` directive.

**Comment by cschwarz007** [comment]
Hi Jonathan,
Amazing how fast you incorporate things. I translated the English names to German and created a pull request...

**Comment by cschwarz007** [comment]
I noted one more issue: When setting a country (e. g. as part of a DAPerson), it is not translated in an attachment properly but still shows in english...

I am generating my attachment as follows:
```
---
mandatory: True
decoration: file-contract
question: |
  Here is your NDA.
subquestion:
  Does this NDA fulfill all your requirements?
field: requirements_fulfilled
buttons:
  - "Yes": True
  - "No": False
attachments:
  - name: NDA
    filename: ${ 'NDA_'+ BDF_company[0].name.text + '_' + Other_party[0].name.text }
    variable name: NDA
    language: ${ doc_lang }
    docx template file: 
      code: |
        template_file
    valid formats:
      - pdf
      - docx
allow emailing: False      
---
```
and have included the country translations in a words file (which is properly included in the configuration and shows in the questions). But in the attachment, the country reads "Germany" and not "Deutschland". Note I use `{{ Other_party[0].address.on_one_line() }}` to generate the address in the template.

**Comment by jhpyle** [comment]
Try 1.1.104 and let me know if it doesn't work right.

**Comment by cschwarz007** [comment]
I am using 1.1.108 now and the document still shows English country names even though `language `for the attachment is set to `de`

**Comment by jhpyle** [comment]
Here is a minimal interview for testing the feature.  Could you try it and let me know the results?
```
initial: True
code: |
  set_language('de')
---
objects:
  - the_address: Address
---
code: |
  the_address.address = '20 Hauptstraße'
  the_address.city = 'Flarchheim'
  the_address.state = 'TH'
  the_address.country = 'DE'
---
mandatory: True
question: |
  Your document
attachment:
  docx template file: de-test.docx
  #language: en
  #language: de
```
The DOCX file is here: [de-test.docx](https://github.com/jhpyle/docassemble/files/5586101/de-test.docx)

Note that you have to use an ISO 3166-1 alpha-2 country code (in this example, `'DE'`).

**Comment by cschwarz007** [comment]
For result please see attachment - country name is still in english. And yes, I am using the ISO 3166-1 country code (upper/lower case does not matter I believe).

[Document.pdf](https://github.com/jhpyle/docassemble/files/5588266/Document.pdf)

**Comment by jhpyle** [comment]
What exactly is your `words` configuration?  Note that if there is a syntax error in a YAML file, it won't be loaded at all and you'll get an error in `uwsgi.log`.  Also it is possible that maybe you are including two files under `words`, one of which has the right translations and one of which has the wrong translations.

The above interview works for me when I have the following in my Configuration and its the only file with `de` translations.
```
words:
  - docassemble.base:data/sources/de-words.yml
```

**Comment by cschwarz007** [comment]
I did some digging into the issue and found my config to be correct - only one words file with `de` translations included.
Rather it seems that - when setting the language directive with a variable - it does not work properly. See code below as example. Anything wrong with my code?

```
objects:
  - the_address: Address
---
code: |
  the_address.address = '20 Hauptstraße'
  the_address.city = 'Flarchheim'
  the_address.state = 'TH'
  the_address.country = 'DE'
---
mandatory: True
need: doc_lang
question: |
  Your document
attachment:
  docx template file: de-test.docx
  language: ${ doc_lang } #this does not give the desired result if variable set to "de"
  # language: de #this gives the desired result
---
question: |
  In which language shall the agreement be drafted?
decoration: globe-europe
field: doc_lang
choices:
  - "English": en
  - "German": de
```

**Comment by jhpyle** [comment]
Sorry, you can't use Mako in a `language` specifier.  You could use `attachment code` and then attach a different attachment depending on the value of `doc_lang`.

**Comment by cschwarz007** [comment]
Got it. And changed my code accordingly. BTW: is there a documentation anywhere which specifiers accept Mako and which don't - for my own education?

**Comment by jhpyle** [comment]
I would assume that a specifier does not accept Mako.  If a specifier accepts Mako, I will usually specify that in the documentation for the specifier, although the documentation might not be totally consistent on that.

**Comment by cschwarz007** [comment]
I am on v 1.2.98 now and the issue of non-translated country names appears again. I sed your above example code and included the words directive as well. However, in the resulting DOCX / PDF the country spells "Germany" instead of (translated) "Deutschland". Maybe something got broken in the meantime?

**Comment by jhpyle** [comment]
I have this in my Configuration:
```
words:
  - docassemble.base:data/sources/de-words.yml
```
I tested this interview:
```
initial: True
code: |
  set_language('de')
---
objects:
  - the_address: Address
---
code: |
  the_address.address = '20 Hauptstraße'
  the_address.city = 'Flarchheim'
  the_address.state = 'TH'
  the_address.country = 'DE'
---
mandatory: True
question: Address
attachment:
  docx template file: de-test.docx
```
The DOCX file is: [de-test.docx](https://github.com/jhpyle/docassemble/files/7001651/de-test.docx)

The result was:

20 Hauptstraße
Flarchheim, TH
Deutschland

I get the same result with:
```
initial: True
code: |
  set_language('en')
---
objects:
  - the_address: Address
---
code: |
  the_address.address = '20 Hauptstraße'
  the_address.city = 'Flarchheim'
  the_address.state = 'TH'
  the_address.country = 'DE'
---
mandatory: True
question: Address
attachment:
  language: de
  docx template file: de-test.docx
```

**Comment by cschwarz007** [comment]
OK - I found the issue: I am using `{{ the_address.block(international=True) }}` in my DOCX template. Apparently, the `international=True` prevents the country from being translated. Is that intended behavior? My intention of setting this is to standardize the address format (e. g. in Germany we do not use states in addresses as they are used in the US). The international modifier outputs the address exactly the way I need it to be for my contracts. Hence if translation can be enabled also for this case it would serve my use case well. Many thanks in advance!

**Comment by jhpyle** [comment]
`international=True` enables the use of the `google-i18n-address` package to standardize the address.  See
https://github.com/mirumee/google-i18n-address
My function returns the string that is returned by the `format_address()` method.  I don't see any option in that package for specifying the language in which the country name is expressed. If `google-i18n-address` had an option for that, I would use it.  You could submit an issue in that repository to ask for that feature, but I don't know if it is even possible because it all depends on a repository of metadata at Google.
If Germany is the only country you work with, you could make yourself a module with:
```
import re

def fix_country(address):
  return re.sub(r'\bGERMANY\b', 'Deutschland', address)  
```
and then any time you used `block()` you would just wrap `fix_country()` around it.

**Comment by cschwarz007** [comment]
Thanks for the background. Unfortunately, this issue is not confined to Germany as we have templates in multiple languages affecting multiple countries (e. g. German template mainly used in Germany, Switzerland, Austria; Spanish template for the Americas and Spain; French template for France and francophone Africa etc...). 

But from looking at [Google's code](https://github.com/mirumee/google-i18n-address/blob/master/i18naddress/__init__.py#L464) it is safe to assume that the country is always the last line of the address returned by `format_address()` is always the last line.

Hence, two options I can think of:

1. Run the last line of what Google returns through the `word()` translation system (which would assume the spelling Google uses matches in every case).
2. Cut off the last line from what Google returns and replace with the mechanism you use when international is set to False. Note that Google returns the country name uppercase (which usually should not make a difference though)

Would any of the two work in your opinion? Unfortunately my Python skills are not goo enough to propose code myself...

**Comment by jhpyle** [comment]
You could create this as `addressfunc.py` in the modules folder:
```
from docassemble.base.util import word
import re

__all__ = ['fix_address']

def fix_address(address):
  if '<w:br/>' in address:
    return re.sub(r'(?<=>)([^>]+)$', lambda m: word(m.group(1)), address)
  return re.sub(r'(?<=NEWLINE\] )([^\]]+)$', lambda m: word(m.group(1)), address)
```
Then you would include it in your YAML with:
```
modules:
  - .addressfunc
```
Then instead of writing `the_address.block(international=True)`, you would write `fix_address(the_address.block(international=True))`.

Then you would need to ensure that the system phrase translation file(s) specified in your Configuration contain translations for each of the upper-case country names that Google might use.

**Comment by cschwarz007** [comment]
Thanks - that works like a charm!
