### ISSUE TITLE
Issue with Geolocate

### ISSUE THREAD

**Issue by cschwarz007** [jhpyle/docassemble#327]
When I run the interview `docassemble.base:data/questions/examples/geolocate-from-address.yml&reset=1` on v1.103 I get the error message below while [on the docassemble demo server it works fine](https://demo.docassemble.org/interview?i=docassemble.base%3Adata%2Fquestions%2Fexamples%2Fgeolocate-from-address.yml#page1). Maybe something broke in the meantime between the version on the demo server and v1.03?
```
Error
Retry

Interview has an error. There was a reference to a variable 'the_address.address' that could not be looked up in the question file (for language 'en') or in any of the files incorporated by reference into the question file.
History
Tried to run mandatory code at 0.00000s
mandatory: True
code: |
  the_address.geolocate(address_one_line)
Needed definition of address_one_line at 0.00004s
Tried to ask question at 0.00012s
question: |
  Enter an address
fields:
  - Address: address_one_line
Completed processing at 0.00029s
Tried to run mandatory code at 0.00059s
mandatory: True
code: |
  the_address.geolocate(address_one_line)
Tried to ask mandatory question at 3.09973s
mandatory: True
question: |
  Information about your address
subquestion: |
  The address you provided is:
    
  ${ the_address }

  The address is located in
  ${ the_address.city }.

  The latitude and longitude are
  ${ the_address.location.latitude }
  and
  ${ the_address.location.longitude }.
Needed definition of the_address.address at 3.10016s
```

**Comment by jhpyle** [comment]
Did you set up the Google API in your Configuration?

**Comment by jhpyle** [comment]
In 1.1.104 I updated the example so that it tests for `geolocate_success` before assuming that the `.address` element exists.

**Comment by cschwarz007** [comment]
Got it. The issue was geocoding was not activated for the google maps api - my fault. Apologies!
