### ISSUE TITLE
Slack link expired

### ISSUE THREAD

**Issue by JonZeolla** [jhpyle/docassemble#335]
The slack link on the website is expired.

https://join.slack.com/t/docassemble/shared_invite/zt-i1z6eg4j-_HFpFnuui_4EtHvKOmSb3A

**Comment by jhpyle** [comment]
Thanks.  Slack is so annoying; the app was telling me the link was good for another three days.  I think I need to come up with a better way of allowing people to join the Slack.  Anyway, the new link is here and I updated it on the web site.

https://join.slack.com/t/docassemble/shared_invite/zt-k144a4z9-50b~iMOFK97yxgn~l28Tsg

**Comment by JonZeolla** [comment]
I run a slack workspace and my approach is:
- Fork [slack-invite-automation](https://github.com/JonZeolla/slack-invite-automation/tree/pittsec) to make some minor stylistic changes.
- Deploy it to Heroku for free or $8/mo to speed up the initial loading times.
- Embed the invite form into the website (see [here](https://pittsec.com/))
