### ISSUE TITLE
Add API endpoint to upload packages to the playground

### ISSUE THREAD

**Issue by JonZeolla** [jhpyle/docassemble#336]
Please add an API endpoint to upload packages to the playground.  Currently the [only supported](https://docassemble.org/docs/api.html#playground_upload) folders are `questions`, `sources`, `static`, `templates`, or `modules`.  This would improve a workflow of developing an interview outside of the playground, and then packaging and uploading it to the playground for testing and debugging.

**Comment by jhpyle** [comment]
This feature was implemented.

**Comment by JonZeolla** [comment]
For posterity the endpoint is `/api/playground_install` - https://docassemble.org/docs/api.html#playground_install
