### ISSUE TITLE
Add a feature to show an index of available interviews

### ISSUE THREAD

**Issue by nonprofittechy** [jhpyle/docassemble#34]
Should most likely take the form of an enhancement to the "Dispatch" directive that already exists:
https://docassemble.org/docs/config.html#dispatch

Improvements could add graphical configuration option or additional menu choices to make it sensible to have this option always turned on. Documentation could be expanded to make the feature more visible.

It should be possible to make the index the default home page for the server hosting Docassemble.

**Comment by luserx0** [comment]
I would like to tackle this one

**Comment by jhpyle** [comment]
See the [`root redirect url`](https://docassemble.org/docs/config.html#root%20redirect%20url) configuration directive, which would allow you to redirect the root of the server to `/list` if you wanted to.
