### ISSUE TITLE
Add a question type that uses the Google Place Autocomplete API

### ISSUE THREAD

**Issue by nonprofittechy** [jhpyle/docassemble#35]
The Google "Place" API allows you to start typing an address and have it automatically fill in the address fields in the form using the location services in your browser. This would increase responsiveness of the interview and make it faster to use.

For the feature, see: https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform

A configuration option should be added to allow you to specify the Google API key. The question type can be completely new, or an option when using an object that implements the Address class.

A possible alternative is using the Open Street Map's implementation of a similar API: http://photon.komoot.de/ or https://help.openstreetmap.org/questions/31809/auto-complete-address-using-web-service. Looks like Google version would be more reliable as the OSM version is host-yourself or use a third-party.

**Comment by shramesh** [comment]
@nonprofittechy I'd love to take this up, but the setup of a local instance of docassemble seems to be gnarly. 

Do you think it'd help for me to make a self-contained SPA which could populate a form with location details?

**Comment by jhpyle** [comment]
That would definitely help, particularly if the server-side code is in Python (docassemble is based on Python/Flask).  If you want to do a pull request, HTML and JS files can go in `docassemble_webapp/docassemble/webapp/static/` and Python can go in `docassemble_webapp/docassemble/webapp/`.

**Comment by jhpyle** [comment]
Implemented.
