### ISSUE TITLE
How can I set the language to Spanish?

### ISSUE THREAD

**Issue by DavidTD1** [jhpyle/docassemble#364]
I put  in docassemble configuration:

language: es
locale: en_US.utf8
os locale: en_US.UTF-8 UTF-8
timezone: America/New_York

But it's not enough

**Comment by jhpyle** [comment]
You also need to use a `words` directive to indicate what system phrase translation files you want to use.
https://docassemble.org/docs/config.html#words

E.g.,
```
words:
  - docassemble.base:data/sources/es-words.xlf
```
The XLF format only works if you are running version 1.2.11 or later.

You can also use YAML for the phrase translation files.  See the Utilities page, which you can access from the menu when you are logged in as an `admin`; you can make your own translation file and edit it.

The XLF file is something I generated using Google Translate, so the translations are probably inaccurate.

It seems a little odd to use `language: es` in the Configuration but use English as the locale, although maybe that is fine.  If you are in the U.S., you might want to keep `language: en` as the default and then use `set_language()` in interviews to change the language to Spanish when necessary.

**Comment by DavidTD1** [comment]
Thank  You
