### ISSUE TITLE
User administration - Profile

### ISSUE THREAD

**Issue by DavidTD1** [jhpyle/docassemble#365]
Good afternoon, I have a question. In the documentation of docassemble it indicates that all registered users can edit their profile information, such as language, first name, last name, country, company.

But in my docassemeble I can't see how I can do that without having administrator privileges. A user with the lowest privilege can only configure her first and last name. The other options do not come out

https://docassemble.org/docs/users.html#profile

**Comment by jhpyle** [comment]
Sorry about that, I forgot to update that page when I changed the behavior. Only users with `developer` or `admin` privileges can edit those additional fields.

You can still read and write those fields with the `user_info()` and `set_user_info()` functions.

**Comment by DavidTD1** [comment]
Ok. For example , if someone with user privilege write her or his name company in a interview with user_info().... that information is update in his/her registration page?

**Comment by DavidTD1** [comment]
Thank you. Its Work
