### ISSUE TITLE
Github email/author

### ISSUE THREAD

**Issue by michaelhofrichter** [jhpyle/docassemble#367]
Hi Jonathan,

I noticed that if I change the Author and Author Email when creating a package in the playground, that only changes those specific fields, but the Long Description/readme.md automatically uses the logged in users name and email address. I just pushed a project my daughter did to github and while the setup.py shows her email in those fields, it shows mine on the readme.md file. 

See https://github.com/michaelhofrichter/docassemble-HarrietTubmanProject/blob/main/setup.py lines 48 to 51.

Thanks

**Comment by jhpyle** [comment]
The `long_description` contains the README, and the README text is editable in the text box in the Playground. When you first create a "package" in the Packages folder it will populate the README text with the name and e-mail of the logged-in user, but that can be edited in the text box when you are looking at the package in the Packages folder.

**Comment by michaelhofrichter** [comment]
Ah, so User Error. Got it. Thanks,
