### ISSUE TITLE
Combobox has no default value if value is not in option list

### ISSUE THREAD

**Issue by beckedorf** [jhpyle/docassemble#369]
If a value in combobox is entered that is not an option, the value will be lost revisiting the question.

Reproduction
============

https://demo.docassemble.org/interview?i=docassemble.base%3Adata%2Fquestions%2Fexamples%2Ffields-choices-combobox.yml#page1

Working example
-----------------

1. Go to the url
2. Choose "Red"
3. Click "Next"
4. Click "Back"

DA behaves as expected: Red is displayed as default value.

Unexpected behaviour
-----------------

1. Go to the url
2. Enter "xxx"
3. Click "Next"
4. Click "Back"

Expected behaviour: "xxx" is displayed as default value
Actual behaviour: The field is empty.

Tested with Chrome 88.0.4324.192 and Safari 14.0.3 (16610.4.3.1.4)

**Comment by jhpyle** [comment]
Thanks.  Try 1.2.37.

**Comment by beckedorf** [comment]
Thanks for the quick response. I just tried it but the behaviour didn't change.

**Comment by jhpyle** [comment]
Sorry about that, my change worked in some contexts but not others.  Try 1.2.38.
