### ISSUE TITLE
`enable if` does not work with `code:`

### ISSUE THREAD

**Issue by beckedorf** [jhpyle/docassemble#371]
Reproduction
==========

If you take this example 

https://github.com/jhpyle/docassemble/blob/master/docassemble_base/docassemble/base/data/questions/examples/showif.yml

and replace `show if:` with `enable if:` or `disable if:` the respective field disappears where it should be visible and disabled.

**Comment by jhpyle** [comment]
I updated the documentation to indicate that `enable if` and `disable if` don't have `code` options.
