### ISSUE TITLE
Ability to change title during interview process, or tags to interviews

### ISSUE THREAD

**Issue by jasonbarbee** [jhpyle/docassemble#40]
It would be nice to be able to add data to the interview title such as a client name, or project. 
So when viewing history of interviews, they are not all the same name. 

My use case may be a little different than legal, I want to use this to generate Statements of Work for contractual labor, so each interview per User would result in a unique client and project name  - and they may want to look up a previous interview.

And/or tags would be a great addition here for a similar result.

**Comment by jhpyle** [comment]
See https://docassemble.org/docs/functions.html#set_title
In 0.1.80 I added a "subtitle" title type and a function `set_title()` that can dynamically change the interview titles.
Tags are a really good idea.  I'll implement that in the future.

**Comment by jhpyle** [comment]
I haven't added tags yet, but I did add the `interview_list()` function, which allows you to get a list of interview sessions.  The interview dictionary is included in the results, as is the interview's metadata.  So you could write your own /interviews page that uses any arbitrary variable from the interview dictionary or the metadata.

https://docassemble.org/docs/functions.html#interview_list
https://docassemble.org/docs/config.html#session%20list%20interview

**Comment by jasonbarbee** [comment]
Thanks, I loaded 1.9.1 and I've tested the set_title() and interview_list() and both work great for my purposes. A user can login and see a default list of interviews, and their history shows a relevant title now.
I'm good if you want to close this initial issue and maybe add a new one for tags if you think that's still relevant.

**Comment by jhpyle** [comment]
I added a "tags" system in 0.1.93.
