### ISSUE TITLE
Problems with defined terms under some circumstances

### ISSUE THREAD

**Issue by Gauntlet173** [jhpyle/docassemble#403]
```
variable name: source
data:
  text1: {defined term}
  text2: a {defined term} that is different
---
mandatory: True
question: This question uses a ${ source['text1'] } and ${ source['text2'] }, and then the {defined term} itself.
terms:
  - defined term: this is the definition.
---
```

If you run the above interview on the latest version, the output looks like this:

<img width="585" alt="Screenshot 2021-05-03 at 3 54 41 PM" src="https://user-images.githubusercontent.com/11790846/116852983-e2943d80-ac27-11eb-9fc9-4c3f57b8f157.png">

It's not clear to me what's going on, there.

**Comment by jhpyle** [comment]
YAML lets you use the `{` and `}` characters to designate an inline dictionary data structure. You just need to be explicit about what you want YAML to interpret as a string:
```
variable name: source
data:
  text1: "{defined term}"
  text2: a {defined term} that is different
```
