### ISSUE TITLE
Playground can't name package in new project

### ISSUE THREAD

**Issue by BryceStevenWilley** [jhpyle/docassemble#406]
I can't seem to name a playground package that doesn't yet have a name (packages with an existing name are fine).

On the latest fresh docker image (1.2.70), I:
* start up the container
* login as admin
* go to the playground and go to "Folders > packages", ending up at `http://localhost/playgroundpackages?project=default`
* type in a valid package name (validation still works okay, and will refuse a name with dashes, etc.), go to the bottom and click save. 

The entered package name won't save. Other changed information, like the URL, author name, and files in the package will save, but the package name will not.

**Comment by jhpyle** [comment]
I think this has been fixed in 1.2.71.

**Comment by BryceStevenWilley** [comment]
Can confirm, 1.2.71 fixes things for me. Thanks for the quick patch!
