### ISSUE TITLE
Cannot change privileges of existing users

### ISSUE THREAD

**Issue by staffanm** [jhpyle/docassemble#409]
In a fresh docker install of docassemble (1.2.73), I can create new privileges and new users, and specify which privileges the newly created users should have. After a user is created however, it is no longer possible to add or remove privileges to that user. It appears to work (the "Information has been saved" message is displayed), but when I edit the user again, none of the changes to their privileges have been saved.

I believe that this issue was introduced in 42b40b4 -- if i reverse this commit just for  docassemble_webapp/docassemble/webapp/users/views.py, it is possible to edit the privileges of an existing user (however, the existing privileges are not shown in the Edit user UI, so it's just an indication, not a fix).

**Comment by jhpyle** [comment]
Sorry, I spent a lot of time on the edit user profile page after upgrading WTForms, but I didn't catch those issues.  I think this is fixed in 1.2.74.

**Comment by staffanm** [comment]
Can confirm that this is fixed in 1.2.74. Thank you for yet another amazingly fast fix!
