### ISSUE TITLE
Automatic Login via 3rd party

### ISSUE THREAD

**Issue by cschwarz007** [jhpyle/docassemble#418]
Hi Jonathan,

Our docassemle setup is one where we use Azure Auth for almost all users (except the standard admin@admin.com).

We have set
```
allow anonymous access: False
password login: false
```

When users go to the docassemble start page, they still have to click on the button "log-in with Azure". Is there any additional configuration directive for users to get redirected to the Azure Auth automatically (saving the clicking of the button)?

**Comment by jhpyle** [comment]
That's the way the cloud-based sign-on works. If it immediately redirected, users may not know why they were suddenly being asked for their Office 365 username and password.
