### ISSUE TITLE
Bug Report "datatype: object"

### ISSUE THREAD

**Issue by lex-rex** [jhpyle/docassemble#42]
Description of the bug:

The easiest way to see the bug/error is to view the following sample interview, which is included in the Docassemble documentation: 

https://demo.docassemble.org/?i=docassemble.demo%3Adata%2Fquestions%2Fexamples%2Fsomeone-already-mentioned.yml#page1

This section of the documentation explains the intended result: 

https://docassemble.org/docs/fields.html#object

My theory as to the cause:

I think the change made on 2017-11-23 has caused the deviation from the intended functionality described in the documentation.  I think setting boolean True or False in multiple choice fields if those are the only options is causing the incompatibility.  I can confirm that this feature works as described in the documentation on a version of Docassemble that I installed prior to the change.  Note that the error does not come up if the multiple choice drop-down is the only field.

The use of the feature described to avoid the redundant entry of data as it pertains to Docassemble objects is one of its most useful features in my opinion.  I will be checking this thread periodically in case anybody needs more information about the bug/error.

Also, thanks to the developer for the fantastic job he has done with this software.

**Comment by jhpyle** [comment]
Thanks!  This has been fixed in 0.2.0.

I really need to expand my [testing scripts](https://github.com/jhpyle/docassemble/blob/master/tests/features/TestExamples.feature) so that I can detect a problem like this before publishing a new version...
