### ISSUE TITLE
accept file .extension instead of MIME

### ISSUE THREAD

**Issue by Ceyar** [jhpyle/docassemble#422]
I wanted to know if there is a solution to use extension name instead of MIME type to pass into the accept attribute of input file.

Default:
```accept="image/png,image/pdf"```

Wanted:
```accept=".png,.pdf"```

Thank you for your help

**Comment by jhpyle** [comment]
The value of the [`accept` specifier](https://docassemble.org/docs/fields.html#accept) is passed directly into the [HTML accept attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#attr-accept), so you can use whatever values the browser will support. Specifying file extensions is supported in the [HTML standard](https://html.spec.whatwg.org/multipage/input.html#file-upload-state-(type=file)).

**Comment by Ceyar** [comment]
Oh I made a mistake sorry. Thank you for taking time.
