### ISSUE TITLE
Calculate button?

### ISSUE THREAD

**Issue by raulvasquez** [jhpyle/docassemble#435]
Is there a way to make a button that doesn't advance you to the next screen, but will run code on the current screen?

Price: price
Partial Payment: payment

Calculate Button: price - partial payment= balance

Balance: balance

I've tried to figure out a way to use the built in functions, and could not figure out a way to make a button that would run the code, but not go to the next question. I did cobbled something together with "check in:" but sometimes does not work reliably.

**Comment by jhpyle** [comment]
Sounds like a task for JavaScript.

```
mandatory: True
question: |
  Tell me stuff
fields:
  - Price: price
    datatype: currency
  - Partial Payment: payment
    datatype: currency
  - note: |
      ${ action_button_html('javascript:calculateIt()', label="Calculate", color="primary", size="sm") }
  - Balance: balance
    datatype: currency
script: |
  <script>
    function calculateIt(){
      if (val('price') !== undefined && val('payment') !== undefined){
        $(getField('balance')).val(parseFloat(val('price')) - parseFloat(val('payment')));
      }
    }
  </script>
```

You could skip the button and add event listeners:

```
mandatory: True
question: |
  Tell me stuff
fields:
  - Price: price
    datatype: currency
  - Partial Payment: payment
    datatype: currency
  - Balance: balance
    datatype: currency
script: |
  <script>
    $(getField('balance')).attr('readonly', true);
    function calculateIt(){
      if (val('price') !== "" && val('payment') !== ""){
        $(getField('balance')).val(parseFloat(val('price')) - parseFloat(val('payment')));
      }
    }
    $(getField('price')).change(calculateIt);
    $(getField('payment')).change(calculateIt);
  </script>
```

**Comment by raulvasquez** [comment]
Thank you. The first solution got me fixed up.

**Comment by jhpyle** [comment]
I'm going back through old issues and I realized I didn't respond to your last point. I think you can get around this by calling `calculate_loan()` when the screen loads.

```
$(document).on('daPageLoad', function(){
  calculate_loan();
});
```
