### ISSUE TITLE
ResponseError does not exist anymore in minio package

### ISSUE THREAD

**Issue by beckedorf** [jhpyle/docassemble#438]
The error in the minio package was refactored which results in the error

```
File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/webapp/createminio.py", line 2, in <module>
    from minio.error import ResponseError, BucketAlreadyOwnedByYou, BucketAlreadyExists
ImportError: cannot import name 'ResponseError' from 'minio.error' (/usr/share/docassemble/local3.8/lib/python3.8/site-packages/minio/error.py)
```

I think they experienced a similar error: https://github.com/IntelLabs/coach/commit/f52ff1784d83b1411cb86d0e7ec4f77a4e711e3d

See
https://github.com/minio/minio-py/commit/77c55f2a9209a4aa4fa35176d602e6f6c5a65495#diff-a464aad3ebf0eb3f35ae3c8670346e45b4b5893a846e017e1ff0d503fcf9c9faL114

**Comment by jhpyle** [comment]
I fixed this but I guess I never followed up here. Sorry about that. Thanks for reporting this.
