### ISSUE TITLE
Show field based on checkboxes

### ISSUE THREAD

**Issue by cschwarz007** [jhpyle/docassemble#442]
Dear all,

I hope you can help me out... I have a list of options, implemented as checkboxes. Multiple selections are possible. If one specific value is checked (famous "other" value), a separate text box shall appear in which the user can enter more details. How can I achieve this?

This is the exemplary yaml of the question:
```
question: |
  Which information is disclosed?`
fields:
  - no label: information
    datatype: checkboxes
    minlength: 1
    choices:
      - Option 1
      - Option 2
      - something else: other
      none of the above: False
```

`show if` does not seem capable of getting specific values of the checked boxes
`js show if` results in val('information') being null (regardless which / how many boxes are checked)

I would need to grab the value via JS or an operator like a show if a variable includes a certain value , like the below which would be in addition to the question definition above

```
  - Elaborate on other: elaboration
    show if:
      variable: information
      includes: other
```

Many thanks in advance for any tips / tricks / ideas...

Regards,
Christian

**Comment by nonprofittechy** [comment]
```
question: |
  Which information is disclosed?`
fields:
  - no label: information
    datatype: checkboxes
    minlength: 1
    choices:
      - Option 1
      - Option 2
      - something else: other
      none of the above: False
  - Elaborate on other: elaboration
    show if: information['Option 1']
```

the variable `information` is a dictionary, and each option is an entry in the dictionary that is either True or False

**Comment by cschwarz007** [comment]
Aaarghhh... That is way too easy (as always in Docassemble). So easy I did not even think it was possible after reading the documentation for `show if`. As always, many thanks for helping me out!
