### ISSUE TITLE
ARM-based Server Package Installation & Management Issue

### ISSUE THREAD

**Issue by Papinian** [jhpyle/docassemble#444]
ARM-based Server - I have an issue upgrading packages & installing packages generally. 

Issue when upgrading / installing a package:
_

> [2021-08-11 10:31:43,268: WARNING/ForkPoolWorker-2] update_packages in worker: starting
> free(): invalid pointer
> [2021-08-11 10:31:49,156: ERROR/MainProcess] Process 'ForkPoolWorker-2' pid:48661 exited with 'signal 6 (SIGABRT)'

_

All processes work as expected except for package installation. Celery, Redis & Rabbitmq are running fine.
Same issue for PyPi & Github & DocAssemble Upgrade. The result is that packages do not install properly and I cannot upgrade docassemble via the UI.

I wonder why we see "free(): invalid pointer". 

Further logs:
_

> [2021-08-10 06:25:41,933: INFO/MainProcess] Connected to amqp://guest:**@[CONTAINER_NAME]:[PORT]//
> [2021-08-10 06:25:41,943: INFO/MainProcess] mingle: searching for neighbors
> [2021-08-10 06:25:42,966: INFO/MainProcess] mingle: all alone
> [2021-08-10 06:25:42,978: INFO/MainProcess] celery@[CONTAINER_NAME] ready.
> [2021-08-10 10:56:26,162: INFO/MainProcess] Received task: docassemble.webapp.worker.update_packages[PACKAGE ID]
> [2021-08-10 10:56:26,163: WARNING/ForkPoolWorker-2] update_packages in worker: starting
> free(): invalid pointer
> [2021-08-10 10:56:32,796: ERROR/MainProcess] Process 'ForkPoolWorker-2' pid:643613 exited with 'signal 6 (SIGABRT)'
> [2021-08-10 10:56:32,809: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: signal 6 (SIGABRT) Job: 0.')
> Traceback (most recent call last):
>   File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/billiard/pool.py", line 1265, in mark_as_worker_lost
>     raise WorkerLostError(
> billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 6 (SIGABRT) Job: 0.

_

**Comment by jhpyle** [comment]
How much RAM does the server have?

**Comment by Papinian** [comment]
> 
> 
> How much RAM does the server have?

24gb. As a test I have since added a huge swap file but it made no difference

**Comment by jhpyle** [comment]
I got that error in another context on ARM and I traced it to the `google.cloud.storage` dependency. So I will disable loading of that module (which will make `DAGoogleAPI` unavailable) outside of amd64. Since I didn't reproduce the error in the same context, I don't know if this will fix this issue, but it is possible that `google.cloud.storage` caused the error you got.

**Comment by Papinian** [comment]
> 
> 
> I got that error in another context on ARM and I traced it to the `google.cloud.storage` dependency. So I will disable loading of that module (which will make `DAGoogleAPI` unavailable) outside of amd64. Since I didn't reproduce the error in the same context, I don't know if this will fix this issue, but it is possible that `google.cloud.storage` caused the error you got.

Thanks Jonathan. I am using Oracle's S3 bucket if that makes a difference, using Amazon's S3 API.

**Comment by Papinian** [comment]
> 
> 
> > I got that error in another context on ARM and I traced it to the `google.cloud.storage` dependency. So I will disable loading of that module (which will make `DAGoogleAPI` unavailable) outside of amd64. Since I didn't reproduce the error in the same context, I don't know if this will fix this issue, but it is possible that `google.cloud.storage` caused the error you got.
> 
> Thanks Jonathan. I am using Oracle's S3 bucket if that makes a difference, using Amazon's S3 API.

I have noticed that a docker restart will actually install the relevant packages. Weird?

**Comment by jhpyle** [comment]
A docker restart will run the `initialize` service inside of `supervisord`. The `initialize` service runs `pip` to make sure that the packages specified in the Package Management list (which is maintained in SQL) are installed on the server. So I'm not sure there is anything weird.

Use of S3 won't be affected by `google.cloud.storage`.

**Comment by Papinian** [comment]
The issue has been resolved Jonathan. Much appreciated!
