### ISSUE TITLE
Security Contact

### ISSUE THREAD

**Issue by MegaManSec** [jhpyle/docassemble#446]
Hi there,

Myself and my colleagues have sent a couple emails to the security contact, outlined in the [security policy](https://github.com/jhpyle/docassemble/security/policy), a few weeks ago, but have not heard back.
Is the information on that page still current?

Thank you.

**Comment by jhpyle** [comment]
Yes.  Was that about the URL for the invite/password change thing?  If so, it's on my to-do list. It's a feature in a Flask dependency.

**Comment by jhpyle** [comment]
I think there was an earlier e-mail (about `next` URL parameters) that it looks like I didn't respond to, although I implemented changes in 1.2.89 as a result of it.

**Comment by MegaManSec** [comment]
Yep, mine was about the invite/password changes. Because we didn't hear a response, we were unsure if it got through or not. Given that it was received, I'll close this now.

Thank you for the continued support and development of docassemble!
