### ISSUE TITLE
Cannot initialize custom image with modified web_app code

### ISSUE THREAD

**Issue by jheyer159** [jhpyle/docassemble#453]
I'm attempting to run a docker container with modified python `docassemble/web_app` code and ran into an issue.  The docker image has not been modified and it's forked from `v1.2.90`

Running `/usr/share/docassemble/webapp/initialize.sh` results in

```This account is currently not available.```

when attempting to `su -c ... www-data` and eventually exits on step `37.1`

it has been resolved by 
* editing `/etc/passwd`
* change the `www-data` account  shell to point to `/bin/bash` instead of `/usr/sbin/nologin`
* re-run `initialize.sh` 

Any idea what would cause `/etc/passwd` to not include `/bin/bash` and preventing the first `initialize.sh`?

Can I avoid this by installing my built python `docassemble/web_app` package into the `jhpyle/docassemble` container without using the shell?

**Comment by jheyer159** [comment]
Rebuilding on a newer commit seems to have resolved this

**Comment by jhpyle** [comment]
The Dockerfile for the `jhpyle/docassemble-os` dependency contains the line `chsh -s /bin/bash www-data`, which gives the `www-data` account the ability to run shell commands. I am not sure which version of `jhpyle/docassemble-os` and `jhpyle/docassemble` you were running, but until I changed it (sometime in the last few months), the `initialize` service would install Debian software updates.  It is possible that the installation of a NGINX update reset the shell of `www-data`.  If you are running the latest Docker image, this sort of thing should not be a problem in the future.
