### ISSUE TITLE
Docker image has not tags

### ISSUE THREAD

**Issue by drewfreyling** [jhpyle/docassemble#458]
It is generally recommended that you tag your docker images (see https://github.com/zegl/kube-score/blob/master/README_CHECKS.md for `container-image-tag` for an example linter that fails because of it). Are we able to get docker tags to match the release versions?

**Comment by jhpyle** [comment]
If the image wasn't so large, I would do that, but it would take up way too much space to make past versions available for download.  (Sometimes I publish multiple versions per day.) If you need a previous version, you can build it.

**Comment by drewfreyling** [comment]
I don't understand how tagging a docker image before pushing it to docker hub takes up space? I checked the pricing and I can't see any limitations there?

**Comment by jhpyle** [comment]
I could tag the latest version with its version ID, but keeping past versions around when they take up 8GB each doesn't make sense.
