### ISSUE TITLE
Support the monaco (vs code) editor in desktop playground?

### ISSUE THREAD

**Issue by nonprofittechy** [jhpyle/docassemble#463]
It is possible to use the VS Code editor embedded in a browser much like codemirror. But it  is a much more robust editor. The main limit is that it is desktop browser only and doesn't support mobile browsers.

Possibly the most useful feature would be search and replace. It looks like more recent versions of codemirror support search and replace as a configurable feature with a plugin, but the interface does not look very good: https://codemirror.net/demo/search.html

**Comment by BryceStevenWilley** [comment]
We discussed this a bit more recently, and might take a look at thinking through monaco/VS code editor vs code mirror (particularly upgrading to CodeMirror 6) a bit more, seeing what might give us the most benefit for updating.

Some resources:
* https://about.sourcegraph.com/blog/migrating-monaco-codemirror, which has [a slightly more technical write up](https://docs.google.com/document/d/1vwR0YnaAv2GOzGg8ggsjUJeKmPZgZv9W-YOFmGnZwxI/edit) of what they got out of CodeMirror 6 vs Monaco
* [the monaco documententation itself](https://microsoft.github.io/monaco-editor/)
* [the migration guide for CodeMirror 5 to 6](https://codemirror.net/docs/migration/

**Comment by nonprofittechy** [comment]
Worth documenting here but after we looked closely at this, it doesn't seem like monaco is clearly better than codemirror so this is probably not a good task to do.
