### ISSUE TITLE
Address Class only allows numbers for ZIP code by default

### ISSUE THREAD

**Issue by cschwarz007** [jhpyle/docassemble#505]
It seems that the address class only allows numbers for the ZIP code field. However, there are countries (e. g. UK) which require letters on top of numbers.

The behavior can be changed through the parameter `datatype`. But it would be better to have this changed dynamically depending on the country selected - is this possible?

**Comment by jhpyle** [comment]
Could you provide some context about where you are seeing this? As far as I am aware, `.zip` is just treated as an optional text attribute with no validation. There is also an option for using `.postal_code` instead. When I ask for a `.zip` portion of an address, I don't set a `datatype` (the default is `datatype: text`). (In the US, some ZIP codes are non-numeric.)

I have not yet figured out how to make a globally-applicable `Address` class or globally-applicable methodology about asking for addresses. JavaScript that will automatically reformat the page based on a country selector would be pretty complicated. It is possible to subclass `Person` and `Address` if the standard classes don't suit your purposes. E.g., you could do:
```
from docassemble.base.util import Person, Address

__all__ = ['UKAddress', 'UKPerson']

class UKAddress(Address):
  def on_one_line(self, include_unit=True, omit_default_country=True, language=None, show_country=None):
    <UK-specific code>
  def block(self, language=None, international=False, show_country=None):
    <UK-specific code>
  def line_one(self, language=None):
    <UK-specific code>
  def line_two(self, language=None):
    <UK-specific code>

class UKPerson(Person):
  AddressClass = UKAddress
```

**Comment by cschwarz007** [comment]
Happy to provide the context: I am gathering contract parties and the following code (excerpt - likely will not run without additions)
```
objects:
  - Other_party: DAList.using(
      object_type=Person,
      there_are_any=True)
---
question:
  Who is the other contract party?
decoration: building
subquestion:
  Please make sure to use the correct and complete legal name of the party (including legal form)!
fields:
  - Company name: Other_party[i].name.text
  - Address: Other_party[i].address.address
  - ZIP Code: Other_party[i].address.zip
  - City: Other_party[i].address.city
  - Country: Other_party[i].address.country
    code: |
      countries_list()
    default: DE
```

results in an input field that has `type=number` set: 
```
<input value="20254" alt="Input box" class="form-control" type="number" step="1" name="QkRGX2NvbXBhbnlbaV0uYWRkcmVzcy56aXA" id="QkRGX2NvbXBhbnlbaV0uYWRkcmVzcy56aXA" data-dashlane-rid="8145ac814f3e8c7d" data-form-type="address,zip" data-kwimpalastatus="alive" data-kwimpalaid="1644235869245-13">
```

Only then I add `datatype = text` the input field consistently remains as text.

As I can not know where in the world the other contract party resides, it would be ideal to dynamically react on the format of the ZIP code that is expected once the country has been selected. I understand that will involve complexity in JavaScript, but that solution would be ideal... Apparently, the CLDR Unicode Library includes RegExes for 158 countries that are supposed to do exactly that: https://github.com/unicode-cldr/cldr-core/blob/27.0.3/supplemental/postalCodeData.json

Another source could be this one: http://download.geonames.org/export/dump/countryInfo.txt

Or (as suggested here) validate based on these rules:

1. Every postal code system uses only A-Z and/or 0-9 and sometimes space/dash
2. Not every country uses postal codes (ex. Ireland outside of Dublin), but we'll ignore that here.
3. The shortest postal code format is Sierra Leone with NN
4. The longest is American Samoa with NNNNN-NNNNNN
5. You should allow one space or dash.
6. Should not begin or end with space or dash

Which results in this regex `(?i)^[a-z0-9][a-z0-9\- ]{0,10}[a-z0-9]$`

**Comment by jhpyle** [comment]
Are you using any browser extensions? Maybe one called "Dashlane"? That HTML does not look like anything my code is producing. This is the HTML that docassemble generates:

```
<div class="da-form-group row darequired da-field-container da-field-container-datatype-text"><label for="T3RoZXJfcGFydHlbaV0uYWRkcmVzcy56aXA" class="col-md-4 col-form-label da-form-label datext-right">ZIP Code</label><div class="col-md-8 dafieldpart"><input alt="Input box" class="form-control" type="text" name="T3RoZXJfcGFydHlbaV0uYWRkcmVzcy56aXA" id="T3RoZXJfcGFydHlbaV0uYWRkcmVzcy56aXA"></div></div>
```

It seems like you have some type of browser extension (or maybe a JavaScript library) that is transforming HTML in the DOM, changing `type="text"` to `type="number"`.

**Comment by cschwarz007** [comment]
Jonathan,
As always, you are on point. I have a browser extension and apparently it mingles with the code (which I did not expect). But then I know who to blame. And thanks for the quick response!
