### ISSUE TITLE
The initialize script does not include ssl settings

### ISSUE THREAD

**Issue by waterfoul** [jhpyle/docassemble#512]
This results in errors any time the psql command is used if ssl enforcement is enabled. See

https://github.com/jhpyle/docassemble/blob/master/Docker/initialize.sh#:~:text=export%20PGHOST%3D%22%24%7BDBHOST,unset%20PGDATABASE

**Comment by jhpyle** [comment]
I am closing this for now but if there are new issues with PostgreSQL and SSL, feel free to reopen. Thanks for letting me know about the issue.
