### ISSUE TITLE
wron translation

### ISSUE THREAD

**Issue by pacodem** [jhpyle/docassemble#519]
https://github.com/jhpyle/docassemble/blob/71291663db930157bcb0dd5beb6f80a56a3ec099/docassemble_base/docassemble/base/data/sources/de-words.yml#L799

"Share" is used as verb, so its better translated "Teilen" instead of "Aktie" in the context that is used in docassemble

**Comment by jhpyle** [comment]
This change was implemented so I am closing the GitHub issue.
