### ISSUE TITLE
How to collect a list of string ?

### ISSUE THREAD

**Issue by ikus060** [jhpyle/docassemble#569]
I tried a lot of stuff before asking and the documentation is not very clear regarding how should I collect a list of string within the same question. I tried to adapt the example here: https://github.com/jhpyle/docassemble/blob/131c7c2b67a35d7d79a72c5197ce9eab928f06ae/docassemble_base/docassemble/base/data/questions/examples/list-collect-string.yml

But without any luck.

It's rater simple. I want to collect a list of string in a question, then generate a docx document that will contain that list.

It seams I fail to understand the concept that "collect" stuff for a DAList.

Help would be appreciated.

My current code is as follow. I want to collect a list of "services"

```
metadata:
  title: "CONTRAT DE PRESTATION DE SERVICE" 
  short title: CONTRAT
  comment: Modèle pour contrat de prestation de service
---
objects:
  client: Individual
  services: DAList.using(minimum_number=1)
---
question: |
  Information du client
mandatory: True
fields:
  - Nom du client: client.name
  - Address: client.address
  - Code Postal: client.zip
  - Ville: client.city
  - Pays: client.country
    code: countries_list()
---
question: |
  Détails de la prestation
mandatory: True
fields:
  - Préciser un service: services[i]
list collect: True
---
question: |
  Voici votre document.
yesno: user_approves
attachment:
  name: Your letter
  filename: letter
  docx template file: contrat-fr.docx
  valid formats:
    - pdf
    - docx
mandatory: True
```

**Comment by jhpyle** [comment]
Your `question` that defines `services[i]` is marked with `mandatory: True`. See the [Gathering information into lists](https://docassemble.org/docs/groups.html#gather%20list) section.
> Nor should you ever use `i` in [`mandatory`](https://docassemble.org/docs/logic.html#mandatory) or [`initial`](https://docassemble.org/docs/logic.html#initial) blocks. The use of `i` is reserved for blocks that docassemble calls upon when it is seeking to define a variable with an index, such as fruit[2], and there is no block that explicitly defines fruit[2]. If you use `i` in a [`mandatory`](https://docassemble.org/docs/logic.html#mandatory) block, you will get an error that `i` is undefined, or if `i` is defined, it might be defined as a value that makes no sense for the context in which you are using `i`.

> For more information on using variables like `i`, see the sections on [index variables](https://docassemble.org/docs/fields.html#index%20variables) and [how docassemble finds questions for variables](https://docassemble.org/docs/logic.html#variablesearching).

If your DOCX file loops over `services`, only your final `question` needs to have `mandatory: True`. See the section on [dependency satisfaction](https://docassemble.org/docs/logic.html#intro_dependency).

**Comment by ikus060** [comment]
Hi @jhpyle 

Thank you very much for this little explanation. It was the little information that was missing to understand how the "no flowchart" works.

I will test this feature today.

I am really grateful for your help.
