### ISSUE TITLE
The demos are experiencing a ProgrammingError

### ISSUE THREAD

**Issue by savagewil** [jhpyle/docassemble#57]
![image](https://user-images.githubusercontent.com/9136637/40073002-9970382e-5843-11e8-8c86-f64efd553dd9.png)

Hi, 
I am working on building a project using disassemble. however as I was working with the documentation, I noticed none of the Demos work. I have not been able to deploy on my environment yet, so I do not know if it is a local issue or a problem with the code.

**Comment by jhpyle** [comment]
Thanks for letting me know -- I updated the software this morning but forgot to make a necessary change to the demo server.  Sorry about that!  It should work now.
