### ISSUE TITLE
Feature Request: Display a discriminator in the "My Interview"

### ISSUE THREAD

**Issue by ikus060** [jhpyle/docassemble#570]
Is it possible to display an identifier in "My interview" to help the user remember which interview it is?

![image](https://user-images.githubusercontent.com/921251/192005274-631629f5-dacd-4bf4-a615-3886fabab2cc.png)

In this examples, having the client name in the table would help user to identify which interview it's for.

**Comment by jhpyle** [comment]
In the interview logic you can do:
```
mandatory: True
code: |
  set_parts(subtitle=client.name.full())
```
and then the "subtitle" will appear in the list in grey, under the title. Or you could change the title.

The "My Interviews" page can be customized. See:
https://docassemble.org/docs/config.html#session%20list%20interview
https://docassemble.org/docs/functions.html#interview_list
https://docassemble.org/docs/config.html#customization

**Comment by ikus060** [comment]
@jhpyle Thanks again for this information.

This application is so flexible ! I get lost with all the documentation available. 

Thanks for helping.
