### ISSUE TITLE
Is it possible for "administrator" or "advocate" to list interview of other users ?

### ISSUE THREAD

**Issue by ikus060** [jhpyle/docassemble#579]
Looking at the documentation, I don't see a way to give permissions to list All the Interviews or other users. Is it a feature available ?

**Comment by jhpyle** [comment]
By default, users with `admin` or `advocate` privileges can access sessions of other users using `interview_list()` or the API. If the interviews use server-side encryption, the decryption key needs to be provided to the API in order for the interview answers in the sessions to be decrypted.

**Comment by ikus060** [comment]
So it's possible to get the list of all interviews from other users using the API or python call.

Is their a way to list the interview using a web interface for non-technical users ? e.g.: I have my advocate that want to review the answer of an interview and possible change the answer given to some question.

**Comment by ikus060** [comment]
Do you have something similar in the examples ?

**Comment by nonprofittechy** [comment]
@ikus060 the task you described has a basic version in @suffolklitlab's ALDashboard project: https://github.com/SuffolkLITLab/docassemble-ALDashboard

**Comment by jhpyle** [comment]
I don't have a recipe for such an administrative interview, but I'll put that on my to-do list.

**Comment by ikus060** [comment]
I will adapt the example from ALDashboard.

Thanks lot for you support.
