### ISSUE TITLE
multilingual documents, lang and locale settings

### ISSUE THREAD

**Issue by gweber2** [jhpyle/docassemble#58]
Hi,

First of all congratulations on an incredible framework and for open-sourcing it!!

I have limited understanding of the processes so apologies if what i'm about to ask is already feasible.
 
The vast majority of documents that we generate will have a text in one language followed by a translation in another language, hence it would be useful if we could set the lang parameter for a date or currency in the template ie "month_of(some_date, as_word=True), **lang=xx**" rather than having the lang parameter automatically set as the default locale settings.

Kind regards

**Comment by jhpyle** [comment]
I am going to close this for now; if the language keyword parameters in the functions are not enough, this issue can be reopened.
