### ISSUE TITLE
Is it possible to edit a "photo" ?

### ISSUE THREAD

**Issue by ikus060** [jhpyle/docassemble#580]
Hello,

I'm testing various way to integrate the collect of multiple photo during the interview and then review the photo at the end.

So far, What I have it working very well, but the "Edit" feature is not working properly for picture. User get prompted to upload a new image, while user might want to only edit the description of the image.

I'm guessing it's related to the input form that doesn't really allow to submit an image as a default value ?

If it's a limitation of HTML and input form, would it be possible to provide a different "question" to allow user to only edit the image description ?

The table with edit button
![image](https://user-images.githubusercontent.com/921251/196523567-58a7a6b2-4c3c-4ad5-a813-8a9d47c2526f.png)

When cliking on Edit. The image field is empty. That prevent user to "continue".
![image](https://user-images.githubusercontent.com/921251/196524029-a2bc4f66-f836-465b-b5b4-91086cd50790.png)

Here the relevant part of the interview:
```
---
objects:
  photos: DAList.using(minimum_number=1, object_type=Thing)
---
question: |
  Voulez-vous prendre une autre photo ?
yesno: photos.there_is_another
---
question: |
  Ajouter une photo
fields:
  - Photo: photos[i].image
    datatype: camera
  - Description: photos[i].name.text
---
mandatory: True
question: |
  Sommaire des photos
subquestion: |
  ${ photos.table }
  
  ${ photos.add_action() }
continue button field: done
---
table: photos.table
rows: photos
columns:
  - Photo: |
      row_item.image
edit:
  - name.text
---
```

**Comment by jhpyle** [comment]
I would recommend using a separate screen for editing the description, and providing a button for uploading a new version of the photo.
```
objects:
  photos: DAList.using(minimum_number=1, object_type=Thing)
---
question: |
  Voulez-vous prendre une autre photo ?
yesno: photos.there_is_another
---
question: |
  Ajouter une photo
fields:
  - Photo: photos[i].image
    datatype: camera
  - Description: photos[i].name.text
---
question: |
  Describe photo
fields:
  - note: |
      ${ photos[i].image }
      ${ action_button_html(url_action(photos[i].attr_name('image')), label="Change photo", icon='pencil', color='secondary') }
  - Description: photos[i].name.text
continue button field: photos[i].photo_edit
---
mandatory: True
question: |
  Sommaire des photos
subquestion: |
  ${ photos.table }
  
  ${ photos.add_action() }
continue button field: done
---
table: photos.table
rows: photos
columns:
  - Photo: |
      str(row_item.image) + '[BR]' + row_item.name.text
edit:
  - photo_edit
```

**Comment by ikus060** [comment]
Brilliant ! I'm still not used to the dependencies resolution way of thinking. 

Thanks will give it a trial and re-open if I need more detail.

**Comment by ikus060** [comment]
Closing as your solution is working great !

Thanks
