### ISSUE TITLE
disable autocomplete globally

### ISSUE THREAD

**Issue by renrom** [jhpyle/docassemble#589]
Hi, is it possible to disable autocomplete for all pages of the interview somewhere?

I don't want the field to be pre-filled in with previous answers.

**Comment by jhpyle** [comment]
I don't have a feature for that currently, but I will add it in the next version.

**Comment by renrom** [comment]
> I don't have a feature for that currently, but I will add it in the next version.

Thanks! that would be great.

**Comment by jhpyle** [comment]
Closing this issue because the feature was added. This was a great idea; thanks for asking about it. I have been using it a lot lately.

https://docassemble.org/docs/initial.html#suppress%20autofill

**Comment by renrom** [comment]
> Closing this issue because the feature was added. This was a great idea; thanks for asking about it. I have been using it a lot lately.
> 
> https://docassemble.org/docs/initial.html#suppress%20autofill

You welcome!
