### ISSUE TITLE
Multiple mail accounts

### ISSUE THREAD

**Issue by cschwarz007** [jhpyle/docassemble#599]
I have a use case where I would want to send from one docassemble instance (same interview even) from two different mail accounts (depending on target user group). It seems though docassemble (currently) only support one mail account for all `send_email` calls. Any way this can be achieved? Many thanks in advance!

**Comment by jhpyle** [comment]
That isn't currently supported but I may be able to add support for that.

**Comment by jhpyle** [comment]
I am closing this because the feature is available as of version 1.4.34, but feel free to reopen if you need further changes to support the way you are e-mailing.
