### ISSUE TITLE
Allow insertion of images into PDF templates

### ISSUE THREAD

**Issue by jhpyle** [jhpyle/docassemble#6]
Currently you can insert images into pandoc-created documents, but not into PDF files that are form-filled.  Use pdftk to allow users to overlay images on top of pages of PDF files.

**Comment by aphelionz** [comment]
Hi again! A quick question about this. If I use the following interview template, the drawn-in signature looks fine but the uploaded signature does not :( It renders very small in the corner of the PDF:

![image](https://user-images.githubusercontent.com/106148/73214289-df0a3080-411f-11ea-8aff-7fdc8df0dc42.png)

I thought it was a matter of using the `da_file[0]` instead of just `da_file` but that didn't seem to make a difference.

Interview template:

```
---
features:
  progress bar: True
---
mandatory: True
code: |
  set_progress(0)
  interview_started
  set_progress(25)
  member_name
  set_progress(50)
  if is_company:
    member_company
    set_progress(75)
  else:
    member_company = "n/a"
    set_progress(75)
  if has_signature_image:
    member_signature_upload
    member_signature = member_signature_upload[0]
  else:
    member_signature
  set_progress(100)
---
id: Intro
question: |
  Welcome!
subquestion: |
  Welcome again.
field: interview_started
---
id: Member Name
question: |
  What is your full name?
fields:
  - Name: member_name
---
id: Is Company
question: |
  Are you part of a company?
yesno: is_company
---
id: Member Company
question: |
  What is the name of your company?
fields:
  - Name: member_company
---
id: Has Signature Image
question: |
  Do you have a signature image to upload?
yesno: has_signature_image
---
id: Member Signature
question: |
  Sign your name using the mouse or your finger.
subquestion: |
  By signing your name, you agree to
  our terms and conditions.
signature: member_signature
under: |
 ${ member_name }
---
question: |
  Please upload a picture of your signature.
fields:
  - Picture: member_signature_upload
    datatype: file
---
id: FinalDoc
question: Here is your document.
allow emailing: false
attachment:
  - name: Membership Agreement (10 Day Pass)
    filename: Membership_Agreement_10_Day_Pass.pdf
    pdf template file: Membership_Agreement_10_Day_Pass.pdf
    fields:
      - "date": ${ format_date(current_datetime(), format='M/d/yyyy')  }
      - "member_name": ${ member_name }
      - "member_company": ${ member_company }
      - "member_signature": ${ member_signature }
mandatory: true
---
```

I assume this is a simple configuration issue, which is why I didn't open another ticket. Thank you!

**Comment by jhpyle** [comment]
@aphelionz I would need to see the Membership_Agreement_10_Day_Pass.pdf file and the file you are uploading to know what's going on.  **docassemble** tries to fit the graphics image into the bounding box of the "Digital Signature" that you create using Adobe Acrobat.  Depending on the relative aspect ratios of the "Digital Signature" and the image, your image could appear smaller or larger.

**Comment by aphelionz** [comment]
Makes sense. This is the PDF I'm working with. I'm using PDF Studio 2019 if that helps.

[Membership Agreement 10 Day Pass.pdf](https://github.com/jhpyle/docassemble/files/4119509/Membership.Agreement.10.Day.Pass.pdf)

**Comment by jhpyle** [comment]
@aphelionz Thanks for letting me know about this.  I figured out the issue.  The signature images generated by the server have no density specified in the metadata, and apparently that is why they work properly, while most other images don't.  The fix will be in the next version.

**Comment by aphelionz** [comment]
Great, thank you!
