### ISSUE TITLE
Idle timer usage

### ISSUE THREAD

**Issue by myaptad** [jhpyle/docassemble#605]
Problem: Idle timer (https://docassemble.org/docs/recipes.html#idle) does not work as expected with "daPageLoad".
Findings: With "daPageLoad" fired at every interview, the script mentioned in this recipe create a new instance of function which updates the same "idleTime" variable. In effect, it's a race condition in which idleTime variable counts faster and faster as user clicks on more screens further down in a multiple page interview. This leads to an unexpectedly quicker timeout of the interview for the user.
Solution: Replacing register with "daPageLoad" to "ready" creates a single instance of anonymous function which updates idleTime, as would be expected for this recipe to work. Hope this helps someone.

**Comment by jhpyle** [comment]
Thanks, I changed it.
