### ISSUE TITLE
Add an "edit this page on GitHub" link to documentation pages

### ISSUE THREAD

**Issue by toolness** [jhpyle/docassemble#62]
When working on #60, it took me a while to realize that the documentation site was stored on the [`gh-pages` branch](https://github.com/jhpyle/docassemble/tree/gh-pages) of the main repository.  One way to make this more discoverable, as well as lower the barrier to contributing to documentation, is to add an "edit this page on GitHub" link somewhere on each documentation page, so that e.g. clicking the link on https://docassemble.org/docs/docker.html would take the user to https://github.com/jhpyle/docassemble/edit/gh-pages/_docs/docker.md.

Since the documentation site seems to be a Jekyll site, I think this should be fairly straightforward and am happy to submit a PR for it if folks think it's a good idea.

**Comment by jhpyle** [comment]
Very good idea.  Thanks!
