### ISSUE TITLE
Multiple Signatures

### ISSUE THREAD

**Issue by renrom** [jhpyle/docassemble#639]
Hi, 

I try to use multiple signatures. After the interview only one signature is safed in the docx template.

This is only a part of the interview:
`--- 
mandatory: true
id: page3
need: verklaring
question: |
   Handtekening
subquestion: |
   Met de ondertekening gaat u akkoord.
signature: handtekening_klant 
under: |
   ${ naam_klant }

continue button label: Volgende
progress: 70
---
mandatory: voogdnodig
question: |
   Handtekening voogd
subquestion: |
   Met de ondertekening gaat u akkoord.
signature: handtekening_voogd
under: |
   ${ voogd_klant }

continue button label: Volgende   
progress: 80
---`

So i have put the signature in variable handtekening_klant and in handtekening_voogd.

Only in the converted PDF it result that only the first signature is there.

I use {{handtekening_klant}} and {{handtekening_voogd}} as variable in the docx file.

**Comment by jhpyle** [comment]
What version of docassemble are you running?

**Comment by renrom** [comment]
> What version of docassemble are you running?

I was running 1.4.36, just upgaded to 1.4.43 but got the same result.

**Comment by jhpyle** [comment]
This interview works fine for me.

```
mandatory: true
question: |
  Handtekening
subquestion: |
  Met de ondertekening gaat u akkoord.
signature: handtekening_klant
---
mandatory: true
question: |
  Handtekening voogd
subquestion: |
  Met de ondertekening gaat u akkoord.
signature: handtekening_voogd
---
mandatory: True
question: |
  Document
attachment:
  docx template file: twosig.docx
```
The document template I am using is here: [twosig.docx](https://github.com/jhpyle/docassemble/files/11124408/twosig.docx)

Do you get the same problem with this example?

If not, perhaps there is something in your interview logic (including logic in DOCX file) that causes the signature not to be displayed. I noticed the second signature is not always `mandatory`.

**Comment by renrom** [comment]
I just tried a small interview with 2 signatures and a simple template and also the template i use normally. It does show the second signature. So somehow it must be somewhere in the interview logic that i go wrong.

The second is indeed not always mandatory :) On some certain choices it is.

Could i send you the xml somehow (allthough it is not in english).

**Comment by renrom** [comment]
Ok, i narrow it down and it seems that it has to do with some code in my interview. if a certain variable is set, then the signature stays empty, even if i have to fill in the signature. it is probebly because of my 'messy' interview so i will try to figure it out.

**Comment by renrom** [comment]
It was indeed a part of code that made the signature clear. Solved it by cleaning up the code.

Thanks for your fast reply!
