### ISSUE TITLE
Upgrade version of pdftk-java in docassemble-os

### ISSUE THREAD

**Issue by nonprofittechy** [jhpyle/docassemble#684]
See discussion here: https://github.com/SuffolkLITLab/docassemble-ALWeaver/issues/871

Manually installing http://ftp.us.debian.org/debian/pool/main/p/pdftk-java/pdftk-java_3.3.3-1_all.deb fixed the issue. There appear to be a number of bugs fixed in this release; given how central pdftk is to Docassemble's operation, it would be worth specially installing from this or a different location given how there's no way other than `exec`ing into the Docker container to install this.

**Comment by jhpyle** [comment]
The latest version updates pdftk. By the way, pdftk has been largely supplanted by pikepdf. It is still used for PDFs that need to be flatted or converted to PDF/A, and it is used for the multiple overlay function.

**Comment by nonprofittechy** [comment]
Got it! Yes, looking closely we did trigger it when adding an overlay
