### ISSUE TITLE
oauth2client in DAOAuth is deprecated

### ISSUE THREAD

**Issue by Gauntlet173** [jhpyle/docassemble#706]
From https://github.com/googleapis/oauth2client/blob/master/CHANGELOG.md, OAuth2Client has been deprecated for 5 years, and should likely be replaced.

**Comment by Gauntlet173** [comment]
OAuth2Client incorrectly makes scopes mandatory, when they are optional in the protocol, making it impossible to use DAOAuth with an API that expects no scope parameter.

**Comment by jhpyle** [comment]
Did you try setting `self.scope = ''`? If so what error message did you get?
