### ISSUE TITLE
Report Line Number in Template Files

### ISSUE THREAD

**Issue by savagewil** [jhpyle/docassemble#71]
It would be nice if line numbers in the template file were reported with template file errors.
![image](https://user-images.githubusercontent.com/9136637/43536926-e985b4e4-958b-11e8-98da-668eb0ea81a9.png)

**Comment by jhpyle** [comment]
.docx files do not have line numbers; they are just one line of XML.  So I'm not sure it would be meaningful to report a line number (it would typically be line 1).  However, it might be possible for `TemplateSyntaxError`s to be raised along with some context, so you could see where in the file the error took place.

The code for that would exist not in the docassemble repository, but in these repositories:

https://github.com/pallets/jinja
https://github.com/elapouya/python-docx-template

**Comment by savagewil** [comment]
Ok, I will look into that

**Comment by jhpyle** [comment]
See elapouya/python-docx-template#134

**Comment by jhpyle** [comment]
This has been implemented about as well is it can be implemented.
