### ISSUE TITLE
Migration to linux/arm64 (rpi4 / Raspberry Pi 4)

### ISSUE THREAD

**Issue by diggidong** [jhpyle/docassemble#725]
Hi everyone,

did somebody else managed to migrate this docker project to linux/arm64 (raspberry pi 4 with 8gb ram)?
When running with default settings, I receive the error:
` ! docassemble The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

If I try to add `-platform: 'linux/arm64`
The docker starts without errors, but keeps restarting every 60 seconds.

Any working solution/migration to linux/arm64?

**Comment by jhpyle** [comment]
See https://docassemble.org/docs/docker.html#arm

**Comment by diggidong** [comment]
well.. RTFM
my fault. thanks a lot!
