### ISSUE TITLE
Update redis-py package requirement to 5.0.2

### ISSUE THREAD

**Issue by NieldSWND** [jhpyle/docassemble#753]
The redis-py 5.0.1 package had a breaking change in that it made its connection callback methods semi-private, which prevented celery from accessing those methods using their original method names and lead to errors like the one attached. This change was reverted in redis-py version 5.0.2. For more on this, see: https://github.com/redis/redis-py/pull/2980

Would you please increment the redis-py version required by docassemble.webapp package to 5.0.2? Until you do, my only workaround to avoid these errors is to manually adjust the celery module every time I rebuild the Docassemble Docker container so as to reference the adjusted, semi-private connection callback methods in redis-py.

[redis-py error.pdf](https://github.com/jhpyle/docassemble/files/14466815/redis-py.error.pdf)

**Comment by jhpyle** [comment]
Sorry about that, I don't test on a redis connection with SSL so this didn't come up in my testing. Thanks for figuring out what the fix was. I upgraded `redis` to 5.0.2 and also upgraded `celery` to the latest version, which may help.
