### ISSUE TITLE
Setting new language doesn´t work

### ISSUE THREAD

**Issue by guidupas** [jhpyle/docassemble#755]
I have set the pt-br language in the configuration file and it does not work. Nothing is translated.

Everything is still in English.

![Screenshot from 2024-03-19 14-12-15](https://github.com/jhpyle/docassemble/assets/12818273/6db705b4-2006-4afb-9b31-e9b7bdb0031c)
![Screenshot from 2024-03-19 14-12-22](https://github.com/jhpyle/docassemble/assets/12818273/34a31904-816e-4ae1-8ece-04569011d2b2)

**Comment by jhpyle** [comment]
What did you set `language` to? https://docassemble.org/docs/config.html#language

**Comment by guidupas** [comment]
Here is the configuration

![Screenshot from 2024-03-19 14-41-24](https://github.com/jhpyle/docassemble/assets/12818273/b65ff629-4075-4e8e-a7d5-dd312ed1ce95)

**Comment by jhpyle** [comment]
The `pt-br-words.yml` file defines translations for the language `pt`, so if you set `language: pt-br`, it won't use the translations in the `pt-br-words.yml` file.

**Comment by guidupas** [comment]
It worked! Thank you very much
