### ISSUE TITLE
Feature Request: seperate out services from Dockerfile

### ISSUE THREAD

**Issue by emansom** [jhpyle/docassemble#767]
Hello, i'd like to run `docassemble` as container and **only docassemble** to run within that container.

This'd allow me to utilize official Postgres, Redis, Celery, RabbitMQ and Apache images for all other services instead: connecting them all together through either `docker-compose`, Podman Pods or Kubernetes Pods.

**Comment by jhpyle** [comment]
All of those services can be externalized. See here for how the Kubernetes implementation does it: https://github.com/jhpyle/charts

**Comment by emansom** [comment]
How exactly does the docker container know to not start its own bundled services(Apache, Postgres, Redis etc.)? If I understand correctly the environment variable `CONTAINERROLE=web:celery` will ensure the container only runs its own web UI?

Thanks for the pointer, the documentation doesn't make it very clear there's an example.

I'd prefer if the official `docassemble` container kept itself very simple and instead would rely on orchestrators (like `docker-compose`, Kubernetes, Nomad) to launch services that it depends upon.

**Comment by jhpyle** [comment]
The Docker container uses `supervisord` and the `initialize` service starts other services based on the value of the `CONTAINERROLE` environment variable.
