### ISSUE TITLE
External Database

### ISSUE THREAD

**Issue by haseebmukhtar** [jhpyle/docassemble#784]
Hi
I am using external database but still local database on container is running.

how can we shutdown local database in container if using external database

**Comment by jhpyle** [comment]
It would be easiest to just ignore the fact that there is a PostgreSQL server on the container doing nothing. It doesn't cause any harm. If you want to prevent it from running you can set a `CONTAINERROLE` that doesn't include `sql`.

**Comment by haseebmukhtar** [comment]
Thanks, I will try CONTAINERROLE.
Need to shutdown PostgreSQL server to reduce the required memory of container.
