### ISSUE TITLE
Remove underlined space from back button

### ISSUE THREAD

**Issue by samglover** [jhpyle/docassemble#790]
This is a minor issue, but when using the text back button there is an underlined space:

<img width="179" alt="Screenshot 2024-07-14 at 1 28 58 PM" src="https://github.com/user-attachments/assets/be20ec18-b677-4e50-99da-75e16e4b4a16">

It doesn't change the usability, but it looks a little odd. I think it looks absolutely fine without the space:

<img width="176" alt="Screenshot 2024-07-14 at 1 31 05 PM" src="https://github.com/user-attachments/assets/5b454cd3-8aee-4892-aaa9-a96b44bb3519">

It looks like removing the space at the end of [this line](https://github.com/jhpyle/docassemble/blob/53e067b3fe8e48f005ce36021563564f1f5a7834/docassemble_base/docassemble/base/standardformatter.py#L825) (after the `</i>`) ought to do it. Or if you wanted some additional space, the [next line](https://github.com/jhpyle/docassemble/blob/53e067b3fe8e48f005ce36021563564f1f5a7834/docassemble_base/docassemble/base/standardformatter.py#L826) could be changed to the following:

```
back_button += '<span class="ms-1">' + status.back + '</span>'
```

That looks pretty similar to the existing spacing, just without the underlined space:

<img width="177" alt="Screenshot 2024-07-14 at 1 38 28 PM" src="https://github.com/user-attachments/assets/297d6719-7917-4aa5-8bf6-b1e3f9f833b4">

If you would consider a pull request (and if I'm right about where the changes need to happen) I'd be happy to submit this minor change.

**Comment by jhpyle** [comment]
Ok I made the change and it will be in the next version.
