### ISSUE TITLE
Sending a static image to DOCX

### ISSUE THREAD

**Issue by renrom** [jhpyle/docassemble#797]
Hi, maybe a simple thing, but i can't figure it out.

Normally if a customer signs a document i can send that with a variable to a docx template. for example:

code in DA:

"question: |
   Signature
subquestion: 
 Please sign
signature: signature_customer "

Then i use {{ signature_customer }} in the docx template to show it up there.

But i also have some 'fixed' signatures from different people where only one will be used. i thought to upload them as static files, for example signer_1.png signer_2.png etc.. 

Then use static_image(variable_signer) somehow to send this also to the same docx template.

i only cannot figure out to use {{ signer? }} to show up the static signature.

**Comment by renrom** [comment]
Ahh.. so the trick is to define it as an object! Thanks a lot for the quick reply!

**Comment by jhpyle** [comment]
That is one of the ways you can insert an image into a DOCX file. See
See https://docassemble.org/docs/documents.html#signature%20docx

**Comment by renrom** [comment]
I did see the documentation but i could not figure out how to use a static image inserting a docx template. If there are other ways to do this, then i want to see some examples aswell as above. (only if you have the time, above solution also works for me, but i am curious about other ways).

**Comment by jhpyle** [comment]
E.g., the DOCX file can contain:
> {{r "[FILE principal_signature.png]" | inline_markdown }}
or
> {{p "[FILE principal_signature.png]" | markdown }}
