### ISSUE TITLE
Parameters i and session are required on session POST

### ISSUE THREAD

**Issue by KyMHP** [jhpyle/docassemble#798]
I can run GET api/session/question with key,i, session and secret which returns the following:

`{
    "message_log": [],
    "questionType": "undefined_variable",
    "variable": "MattersFeeEarnerRef"
}`

But when I try to set the variable using POST api/session with the same i, session, secret and parameters set as {"MattersFeeEarnerRef":"TEST"}, then I get the response:

400: "Parameters i and session are required."

**Comment by jhpyle** [comment]
See https://docassemble.org/docs/api.html#post
On a POST request the URL parameters are not used.

**Comment by KyMHP** [comment]
Ok, that was it. Thank you
