### ISSUE TITLE
Package version number not being updated?

### ISSUE THREAD

**Issue by kyle-rhodes** [jhpyle/docassemble#804]
When I install a package on my Docassemble server via Github, Docassemble (v1.6.2) reports the version number as 0.0.1 regardless of the version number in __init__.py.

![image](https://github.com/user-attachments/assets/fdd016a3-7af8-4515-a45a-7853e13da04f)

I've tried installing from a public and private responsitory with the same results. Here is the public repository I used for a test: 

https://github.com/familylegacyguard/docassemble-TestPrivateVersion

**Comment by jhpyle** [comment]
The version of a Python package is determined by the `setup.py` file. There is a convention of indicating the version number in the `__init__.py` file, but that is just a convention.
![image](https://github.com/user-attachments/assets/9bc1bfcd-0812-438b-9bb0-c18fe1d1b521)

**Comment by kyle-rhodes** [comment]
I figured it might be my mistake. :) Thanks!
