### ISSUE TITLE
Python function that converts a Python data structure to .xlsx

### ISSUE THREAD

**Issue by jhpyle** [jhpyle/docassemble#90]
Write (or find) a helper function that takes either 1) an array of arrays, plus an array of headers; or 2) an array of dicts, and produces an Excel file with table headers and appropriate cell formatting.  This could be useful for getting information out of Python.

**Comment by deadpyxel** [comment]
Is there any restriction about modules or libraries?

**Comment by jhpyle** [comment]
`pandas` and `numpy` are already dependencies of `docassemble.webapp`, so that should be fine.  The code would need to be thread-safe, and my understanding is that there are some thread safety issues with pandas, though those issues might not arise in the context of a helper function that builds an XLSX file.

**Comment by gururajbn** [comment]
hi @jhpyle is this issue still open?  I think this can easily done using `tablib` module.

**Comment by jhpyle** [comment]
Thanks!  The `tablib` module looks great.  Maybe the task is just to write a helper function that uses tablib and integrates as necessary with docassemble `DADict` and `DAList` objects and writes to a `DAFile`.

**Comment by jhpyle** [comment]
The function can go in [util.py](https://github.com/jhpyle/docassemble/blob/master/docassemble_base/docassemble/base/util.py) and it will need to call `pandas` or `tablib` in such a way that it can process pseudo-lists and pseduo-dicts (`DAList` and `DADict`) objects, and it will need to produce a `DAFile` object.  See the [objects page of the documentation](https://docassemble.org/docs/objects.html) for instructions on using docassemble objects.
