### ISSUE TITLE
Feature Request: Add a configuration option to change the default logged in screen

### ISSUE THREAD

**Issue by epompeii** [jhpyle/docassemble#92]
As the title suggests, this request is for a configuration option that allows an admin to set the default logged in screen based off of one's role. Right now, all users are directed to the My Interviews screen. This is great for the client end users of the system. However those in other roles may find a different landing page more useful.

With this feature, one would be able to have a configuration option like this:

```
Landing page:
    admin: User List
    developer: Playground
    advocate: Monitor
    trainer: Train
    user: My Interviews
```

**Comment by jhpyle** [comment]
Implemented as the `page after login` configuration directive in 0.3.10.
